### ISSUE TITLE
Manual (FreeBSD) Instructions

### ISSUE THREAD

**Issue by rustikles** [teslamate-org/teslamate#2224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Following wiki instructions and issuing "service teslamate start". Fails cube.control extenion control file. Unable to access teslamate service at locahost:4000.

### Relevant log output

```shell
warning: a term is constructed, but never used
  usr/local/src/teslamate/_build/prod/rel/teslamate/lib/teslamate-1.25.0/priv/repo/migrations/20190925182253_add_geofence_id_to_addresses.exs

2021-12-16 07:09:44.963 [info] == Running 20190925152807 TeslaMate.Repo.Migrations.CreateGeoExtensions.change/0 forward
2021-12-16 07:09:44.965 [info] execute "CREATE EXTENSION IF NOT EXISTS cube"
** (Postgrex.Error) ERROR 58P01 (undefined_file) could not open extension control file "/usr/local/share/postgresql/extension/cube.control": No such file or directory
    (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:760: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.11.4) lib/enum.ex:1411: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:852: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.7.1) lib/ecto/migration/runner.ex:343: Ecto.Migration.Runner.log_and_execute_ddl/3
    (ecto_sql 3.7.1) lib/ecto/migration/runner.ex:117: anonymous fn/6 in Ecto.Migration.Runner.flush/0
    (elixir 1.11.4) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto_sql 3.7.1) lib/ecto/migration/runner.ex:116: Ecto.Migration.Runner.flush/0
    (ecto_sql 3.7.1) lib/ecto/migration/runner.ex:280: Ecto.Migration.Runner.perform_operation/3
```

### Type of installation

Manual

### Version

1.25.0

**Comment by rustikles** [comment]
Verified postgresql13-server port does not include cube.control extension by default. Still investigating the reason. https://cgit.freebsd.org/ports/tree/databases/postgresql13-server/pkg-plist-server

**Comment by rustikles** [comment]
Additional control files available under postgresql13-contrib in ports tree. Will issue pull request with instructions if I get everything working.
