### ISSUE TITLE
After being parked 24hrs in underground parking and being OFFLINE, Teslamate failed to catch any car update once the car was expected to be online

### ISSUE THREAD

**Issue by manikoutai** [teslamate-org/teslamate#2616]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After the car was parked inside underground parking, Teslamate set the car status as OFFLINE.

The car remains in such place for 24hrs.

Once the car was back on the street, driving it for 500 km never lead to teslamate to catch the car new status.  It was only several hours later, once I was home, that restarting teslamate and the raspberry pi, that teslamate was finally able to get back some information about the car once again.

Please note that I have put a complete Log + several screenshots inside of the following discussion:  https://github.com/adriankumpf/teslamate/discussions/2614 

### Expected Behavior

The fact that the car was appearing as OFFLINE while the car was parked in the underground parking was expected.

Once the car was back on the street, at the ground level, teslamate should have been able to get new status about the car.  A restart of the teslamate shouldn't be required.

The car was back to the street on April 22nd at 14:25hrs and teslamate was expected to acknowledge that the car was no longer OFFLINE.

### Relevant log output

```shell
Here I move the car from the street down to the underground parking (i.e. we see Driving start)

�[36mteslamate_1  |�[0m 2022-04-21 18:42:55.104 car_id=1 [info] Driving / Start
�[36mteslamate_1  |�[0m 2022-04-21 18:45:55.337 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/1492656516736953/vehicle_data -> 408 (9194.391 ms)
�[36mteslamate_1  |�[0m 2022-04-21 18:45:55.338 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
�[36mteslamate_1  |�[0m 2022-04-21 18:45:55.339 car_id=1 [error] Error / :unknown
�[36mteslamate_1  |�[0m 2022-04-21 18:45:58.988 [error] Vehicle Error: Vehicle is offline
�[36mteslamate_1  |�[0m 2022-04-21 18:46:46.766 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/1492656516736953/vehicle_data -> 408 (9186.213 ms)
�[36mteslamate_1  |�[0m 2022-04-21 18:46:46.767 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
�[36mteslamate_1  |�[0m 2022-04-21 18:46:46.767 car_id=1 [error] Error / :unknown
�[36mteslamate_1  |�[0m 2022-04-21 18:47:05.965 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/1492656516736953/vehicle_data -> 408 (9193.922 ms)
�[36mteslamate_1  |�[0m 2022-04-21 18:47:05.967 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
�[36mteslamate_1  |�[0m 2022-04-21 18:47:05.968 car_id=1 [error] Error / :unknown
�[36mteslamate_1  |�[0m 2022-04-21 18:47:06.909 car_id=1 [info] Received stream data: :inactive
�[36mteslamate_1  |�[0m 2022-04-21 18:47:25.162 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/1492656516736953/vehicle_data -> 408 (9190.792 ms)
�[36mteslamate_1  |�[0m 2022-04-21 18:47:25.164 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
�[36mteslamate_1  |�[0m 2022-04-21 18:47:25.165 car_id=1 [error] Error / :unknown
�[36mteslamate_1  |�[0m 2022-04-21 18:47:30.011 [notice]     :alarm_handler: {:set, {TeslaMate.Vehicles.Vehicle_1_api_error, :fuse_blown}}
�[36mteslamate_1  |�[0m 2022-04-21 18:47:44.374 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/1492656516736953/vehicle_data -> 408 (9206.122 ms)
�[36mteslamate_1  |�[0m 2022-04-21 18:47:44.376 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
�[36mteslamate_1  |�[0m 2022-04-21 18:47:44.377 car_id=1 [error] Error / :unknown
�[36mteslamate_1  |�[0m 2022-04-21 18:48:03.569 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/1492656516736953/vehicle_data -> 408 (9189.122 ms)
�[36mteslamate_1  |�[0m 2022-04-21 18:48:03.571 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
�[36mteslamate_1  |�[0m 2022-04-21 18:48:03.571 car_id=1 [error] Error / :unknown
�[36mteslamate_1  |�[0m 2022-04-21 18:48:09.039 [error] Vehicle Error: Vehicle is offline
�[36mteslamate_1  |�[0m 2022-04-21 18:48:13.747 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/1492656516736953/vehicle_data -> 408 (172.894 ms)
�[36mteslamate_1  |�[0m 2022-04-21 18:48:13.955 car_id=1 [warning] Vehicle went offline while driving
�[36mteslamate_1  |�[0m 2022-04-21 18:48:19.146 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/1492656516736953/vehicle_data -> 408 (187.554 ms)
�[36mteslamate_1  |�[0m 2022-04-21 18:48:24.546 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/1492656516736953/vehicle_data -> 408 (199.495 ms)
�[36mteslamate_1  |�[0m 2022-04-21 18:48:29.942 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/1492656516736953/vehicle_data -> 408 (188.460 ms)
�[36mteslamate_1  |�[0m 2022-04-21 18:48:35.576 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/1492656516736953/vehicle_data -> 408 (442.545 ms)
�[36mteslamate_1  |�[0m 2022-04-21 18:48:39.833 [error] Vehicle Error: Vehicle is offline

Then it was unable to refresh the token:

�[36mteslamate_1  |�[0m 2022-04-21 19:13:08.012 [error] Vehicle Error: Vehicle is offline
�[36mteslamate_1  |�[0m 2022-04-21 19:13:17.507 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/1492656516736953/vehicle_data -> 408 (174.675 ms)
�[36mteslamate_1  |�[0m 2022-04-21 19:13:38.755 [error] ** (RuntimeError) Client Error: %{"error_type" => "client_error", "msg_type" => "data:error", "tag" => "276117568696", "value" => "Can't validate token. "}
�[36mteslamate_1  |�[0m     (teslamate 1.26.1) lib/tesla_api/stream.ex:165: TeslaApi.Stream.handle_frame/2
�[36mteslamate_1  |�[0m     (websockex 0.4.3) lib/websockex.ex:1113: WebSockex.try_callback/3
�[36mteslamate_1  |�[0m     (websockex 0.4.3) lib/websockex.ex:797: WebSockex.common_handle/4
�[36mteslamate_1  |�[0m     (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
�[36mteslamate_1  |�[0m 
�[36mteslamate_1  |�[0m 2022-04-21 19:13:39.005 car_id=1 [info] Start / :offline


Then TeslaMate could not access the API endpoint.
�[36mteslamate_1  |�[0m 2022-04-22 23:00:53.854 [warning] Retrying in 5 minutes...
�[36mteslamate_1  |�[0m 2022-04-22 23:00:54.546 [error] GET https://owner-api.teslamotors.com/api/1/vehicles/1492656516736953 -> error: "non-existing domain" (8013.844 ms)
�[36mteslamate_1  |�[0m 2022-04-22 23:00:54.547 [warning] TeslaApi.Error / non-existing domain
�[36mteslamate_1  |�[0m 2022-04-22 23:00:54.547 car_id=1 [error] Error / :unknown
�[36mteslamate_1  |�[0m 2022-04-22 23:01:32.567 [error] GET https://owner-api.teslamotors.com/api/1/vehicles/1492656516736953 -> error: "non-existing domain" (8014.068 ms)
�[36mteslamate_1  |�[0m 2022-04-22 23:01:32.567 [warning] TeslaApi.Error / non-existing domain
�[36mteslamate_1  |�[0m 2022-04-22 23:01:32.568 car_id=1 [error] Error / :unknown
�[36mteslamate_1  |�[0m 2022-04-22 23:02:10.585 [error] GET https://owner-api.teslamotors.com/api/1/vehicles/1492656516736953 -> error: "non-existing domain" (8013.787 ms)
�[36mteslamate_1  |�[0m 2022-04-22 23:02:10.586 [warning] TeslaApi.Error / non-existing domain
�[36mteslamate_1  |�[0m 2022-04-22 23:02:10.586 car_id=1 [error] Error / :unknown
�[36mteslamate_1  |�[0m 2022-04-22 23:02:48.605 [error] GET https://owner-api.teslamotors.com/api/1/vehicles/1492656516736953 -> error: "non-existing domain" (8013.880 ms)
�[36mteslamate_1  |�[0m 2022-04-22 23:02:48.606 [warning] TeslaApi.Error / non-existing domain
�[36mteslamate_1  |�[0m 2022-04-22 23:02:48.606 car_id=1 [error] Error / :unknown
�[36mteslamate_1  |�[0m 2022-04-22 23:03:26.624 [error] GET https://owner-api.teslamotors.com/api/1/vehicles/1492656516736953 -> error: "non-existing domain" (8014.046 ms)
�[36mteslamate_1  |�[0m 2022-04-22 23:03:26.625 [warning] TeslaApi.Error / non-existing domain
�[36mteslamate_1  |�[0m 2022-04-22 23:03:26.625 car_id=1 [error] Error / :unknown
�[36mteslamate_1  |�[0m 2022-04-22 23:04:04.643 [error] GET https://owner-api.teslamotors.com/api/1/vehicles/1492656516736953 -> error: "non-existing domain" (8013.897 ms)
�[36mteslamate_1  |�[0m 2022-04-22 23:04:04.644 [warning] TeslaApi.Error / non-existing domain
�[36mteslamate_1  |�[0m 2022-04-22 23:04:04.644 car_id=1 [error] Error / :unknown
�[36mteslamate_1  |�[0m 2022-04-22 23:04:42.662 [error] GET https://owner-api.teslamotors.com/api/1/vehicles/1492656516736953 -> error: "non-existing domain" (8013.950 ms)
�[36mteslamate_1  |�[0m 2022-04-22 23:04:42.663 [warning] TeslaApi.Error / non-existing domain
�[36mteslamate_1  |�[0m 2022-04-22 23:04:42.663 car_id=1 [error] Error / :unknown
�[36mteslamate_1  |�[0m 2022-04-22 23:05:20.685 [error] GET https://owner-api.teslamotors.com/api/1/vehicles/1492656516736953 -> error: "non-existing domain" (8017.884 ms)
�[36mteslamate_1  |�[0m 2022-04-22 23:05:20.686 [warning] TeslaApi.Error / non-existing domain
�[36mteslamate_1  |�[0m 2022-04-22 23:05:20.686 car_id=1 [error] Error / :unknown
�[36mteslamate_1  |�[0m 2022-04-22 23:05:53.856 [info] Refreshing access token ...
�[36mteslamate_1  |�[0m 2022-04-22 23:05:58.704 [error] GET https://owner-api.teslamotors.com/api/1/vehicles/1492656516736953 -> error: "non-existing domain" (8013.802 ms)
�[36mteslamate_1  |�[0m 2022-04-22 23:05:58.705 [warning] TeslaApi.Error / non-existing domain
�[36mteslamate_1  |�[0m 2022-04-22 23:05:58.705 car_id=1 [error] Error / :unknown
�[36mteslamate_1  |�[0m 2022-04-22 23:06:01.872 [error] POST https://auth.tesla.com/oauth2/v3/token -> error: "non-existing domain" (8014.368 ms)
�[36mteslamate_1  |�[0m 2022-04-22 23:06:01.873 [warning] Token refresh failed: %TeslaApi.Error{
�[36mteslamate_1  |�[0m   env: nil,
�[36mteslamate_1  |�[0m   message: "non-existing domain",
�[36mteslamate_1  |�[0m   reason: :token_refresh
�[36mteslamate_1  |�[0m }
�[36mteslamate_1  |�[0m 2022-04-22 23:06:01.873 [warning] Retrying in 5 minutes...
�[36mteslamate_1  |�[0m 2022-04-22 23:06:36.723 [error] GET https://owner-api.teslamotors.com/api/1/vehicles/1492656516736953 -> error: "non-existing domain" (8013.926 ms)
�[36mteslamate_1  |�[0m 2022-04-22 23:06:36.724 [warning] TeslaApi.Error / non-existing domain
�[36mteslamate_1  |�[0m 2022-04-22 23:06:36.725 car_id=1 [error] Error / :unknown
�[36mteslamate_1  |�[0m 2022-04-22 23:07:14.742 [error] GET https://owner-api.teslamotors.com/api/1/vehicles/1492656516736953 -> error: "non-existing domain" (8013.911 ms)
�[36mteslamate_1  |�[0m 2022-04-22 23:07:14.743 [warning] TeslaApi.Error / non-existing domain
�[36mteslamate_1  |�[0m 2022-04-22 23:07:14.743 car_id=1 [error] Error / :unknown
�[36mteslamate_1  |�[0m 2022-04-22 23:07:52.760 [error] GET https://owner-api.teslamotors.com/api/1/vehicles/1492656516736953 -> error: "non-existing domain" (8013.931 ms)
�[36mteslamate_1  |�[0m 2022-04-22 23:07:52.761 [warning] TeslaApi.Error / non-existing domain
�[36mteslamate_1  |�[0m 2022-04-22 23:07:52.762 car_id=1 [error] Error / :unknown
�[36mteslamate_1  |�[0m 2022-04-22 23:08:30.781 [error] GET https://owner-api.teslamotors.com/api/1/vehicles/1492656516736953 -> error: "non-existing domain" (8014.058 ms)
�[36mteslamate_1  |�[0m 2022-04-22 23:08:30.781 [warning] TeslaApi.Error / non-existing domain
�[36mteslamate_1  |�[0m 2022-04-22 23:08:30.781 car_id=1 [error] Error / :unknown
�[36mteslamate_1  |�[0m 2022-04-22 23:09:08.799 [error] GET https://owner-api.teslamotors.com/api/1/vehicles/1492656516736953 -> error: "non-existing domain" (8013.961 ms)
�[36mteslamate_1  |�[0m 2022-04-22 23:09:08.800 [warning] TeslaApi.Error / non-existing domain
�[36mteslamate_1  |�[0m 2022-04-22 23:09:08.800 car_id=1 [error] Error / :unknown
�[36mteslamate_1  |�[0m 2022-04-22 23:09:46.818 [error] GET https://owner-api.teslamotors.com/api/1/vehicles/1492656516736953 -> error: "non-existing domain" (8013.961 ms)
�[36mteslamate_1  |�[0m 2022-04-22 23:09:46.819 [warning] TeslaApi.Error / non-existing domain
�[36mteslamate_1  |�[0m 2022-04-22 23:09:46.819 car_id=1 [error] Error / :unknown
�[36mteslamate_1  |�[0m 2022-04-22 23:10:24.837 [error] GET https://owner-api.teslamotors.com/api/1/vehicles/1492656516736953 -> error: "non-existing domain" (8013.943 ms)
�[36mteslamate_1  |�[0m 2022-04-22 23:10:24.838 [warning] TeslaApi.Error / non-existing domain
�[36mteslamate_1  |�[0m 2022-04-22 23:10:24.838 car_id=1 [error] Error / :unknown
�[36mteslamate_1  |�[0m 2022-04-22 23:11:01.874 [info] Refreshing access token ...
�[36mteslamate_1  |�[0m 2022-04-22 23:11:02.855 [error] GET https://owner-api.teslamotors.com/api/1/vehicles/1492656516736953 -> error: "non-existing domain" (8013.736 ms)
�[36mteslamate_1  |�[0m 2022-04-22 23:11:02.856 [warning] TeslaApi.Error / non-existing domain
�[36mteslamate_1  |�[0m 2022-04-22 23:11:02.856 car_id=1 [error] Error / :unknown
�[36mteslamate_1  |�[0m 2022-04-22 23:11:09.891 [error] POST https://auth.tesla.com/oauth2/v3/token -> error: "non-existing domain" (8015.027 ms)
�[36mteslamate_1  |�[0m 2022-04-22 23:11:09.892 [warning] Token refresh failed: %TeslaApi.Error{
�[36mteslamate_1  |�[0m   env: nil,
�[36mteslamate_1  |�[0m   message: "non-existing domain",
�[36mteslamate_1  |�[0m   reason: :token_refresh
�[36mteslamate_1  |�[0m }
�[36mteslamate_1  |�[0m 2022-04-22 23:11:09.892 [warning] Retrying in 5 minutes...


Restarting the raspberry Pi resolved the situation:
�[36mteslamate_1  |�[0m 2022-04-23 11:00:12.489 car_id=1 [error] Error / :unknown
�[36mteslamate_1  |�[0m 2022-04-23 11:00:50.507 [error] GET https://owner-api.teslamotors.com/api/1/vehicles/1492656516736953 -> error: "non-existing domain" (8013.777 ms)
�[36mteslamate_1  |�[0m 2022-04-23 11:00:50.508 [warning] TeslaApi.Error / non-existing domain
�[36mteslamate_1  |�[0m 2022-04-23 11:00:50.509 car_id=1 [error] Error / :unknown
�[36mteslamate_1  |�[0m waiting for postgres at database:5432
�[36mteslamate_1  |�[0m waiting for postgres at database:5432
�[36mteslamate_1  |�[0m waiting for postgres at database:5432
�[36mteslamate_1  |�[0m waiting for postgres at database:5432
�[36mteslamate_1  |�[0m 2022-04-23 10:17:56.874 [info] Migrations already up
�[36mteslamate_1  |�[0m 2022-04-23 10:18:06.326 [info] System Info: Erlang/OTP 24 (emu)
�[36mteslamate_1  |�[0m 2022-04-23 10:18:06.327 [info] Version: 1.26.1
�[36mteslamate_1  |�[0m 2022-04-23 10:18:14.769 [error] POST https://auth.tesla.com/oauth2/v3/token -> error: "non-existing domain" (8172.368 ms)
�[36mteslamate_1  |�[0m 2022-04-23 10:18:14.771 [warning] Token refresh failed: %TeslaApi.Error{
�[36mteslamate_1  |�[0m   env: nil,
�[36mteslamate_1  |�[0m   message: "non-existing domain",
�[36mteslamate_1  |�[0m   reason: :token_refresh
�[36mteslamate_1  |�[0m }
�[36mteslamate_1  |�[0m 2022-04-23 10:18:14.772 [info] Scheduling token refresh in 7 min
�[36mteslamate_1  |�[0m 2022-04-23 10:18:14.831 [info] Running TeslaMateWeb.Endpoint with cowboy 2.9.0 at :::4000 (http)
�[36mteslamate_1  |�[0m 2022-04-23 10:18:14.847 [info] Access TeslaMateWeb.Endpoint at http://localhost
�[36mteslamate_1  |�[0m 2022-04-23 10:18:22.871 [error] GET https://owner-api.teslamotors.com/api/1/vehicles -> error: "non-existing domain" (8015.045 ms)
�[36mteslamate_1  |�[0m 2022-04-23 10:18:22.871 [warning] TeslaApi.Error / non-existing domain
�[36mteslamate_1  |�[0m 2022-04-23 10:18:22.872 [warning] Could not get vehicles: :unknown
�[36mteslamate_1  |�[0m 2022-04-23 10:18:22.928 [warning] Using fallback vehicles:
�[36mteslamate_1  |�[0m 
�[36mteslamate_1  |�[0m [
�[36mteslamate_1  |�[0m   %TeslaApi.Vehicle{
�[36mteslamate_1  |�[0m     api_version: nil,
�[36mteslamate_1  |�[0m     backseat_token: nil,
�[36mteslamate_1  |�[0m     backseat_token_updated_at: nil,
�[36mteslamate_1  |�[0m     calendar_enabled: nil,
�[36mteslamate_1  |�[0m     charge_state: nil,
�[36mteslamate_1  |�[0m     climate_state: nil,
�[36mteslamate_1  |�[0m     color: nil,
�[36mteslamate_1  |�[0m     display_name: "Schtroumpf Electrique",
�[36mteslamate_1  |�[0m     drive_state: nil,
�[36mteslamate_1  |�[0m     gui_settings: nil,
�[36mteslamate_1  |�[0m     id: 1492656516736953,
�[36mteslamate_1  |�[0m     in_service: false,
�[36mteslamate_1  |�[0m     option_codes: [],
�[36mteslamate_1  |�[0m     state: "unknown",
�[36mteslamate_1  |�[0m     tokens: [],
�[36mteslamate_1  |�[0m     vehicle_config: nil,
�[36mteslamate_1  |�[0m     vehicle_id: 276117568696,
�[36mteslamate_1  |�[0m     vehicle_state: nil,
�[36mteslamate_1  |�[0m     vin: "5YJ3E1EA6NF152959"
�[36mteslamate_1  |�[0m   }
�[36mteslamate_1  |�[0m ]
�[36mteslamate_1  |�[0m 2022-04-23 10:18:22.928 [info] Starting logger for 'Schtroumpf Electrique'
�[36mteslamate_1  |�[0m 2022-04-23 10:18:23.133 [info] MQTT connection has been established
```

### Type of installation

Docker

### Version

v1.26.1

**Comment by manikoutai** [comment]
This is the offline state as visible from teslamate: 
![image](https://user-images.githubusercontent.com/103542406/165599760-13360a1f-120d-43c3-8725-ce0ff590e248.png)

I am attaching the full log, as generated when I reported the situation in the Q&A section
[teslamate_log.txt](https://github.com/adriankumpf/teslamate/files/8575671/teslamate_log.txt)

Please note a **4 hours difference between the log time and the teslamate UI time** (I still need to figure out how to prevent this difference).

**Comment by woyteck1** [comment]
Did you access your app during that time? I have noticed that accessing app sometimes re-enables Tesla API so it restarts the Teslamate scraping

**Comment by manikoutai** [comment]
@woyteck1 By "App" I presume you are referring to the Tesla app?  Yes, I did use it several time during the day I was returning home. I took some screenshots each time I was at a super chargers, so multiple utilisation of the app during the day for sure.

**Comment by mnadvornik** [comment]
@manikoutai the error `non-existing domain` indicates that teslamate wasn't able to resolve owner-api.teslamotors.com. This means your DNS server (be it docker internal, or whatever the DNS Server in your infrastrucure is) was not able to return a record. I can't think of a reason how this should be caused by teslamate. Could it be that your raspi ran out of resources or lost internet access during that time?
You will probably also have some indication in `/var/log/syslog`

**Comment by manikoutai** [comment]
> 

@mnadvornik ,

Thanks for looking into this and to provide some suggestions. 

Unfortunately, there is nothing in /var/log/syslog so far in the past since it seems to contain only 3-4 days of log.

I can't tell exactly what was wrong with the pi and the only thing that I was able to do was to restart it.

The non-existing domain error seems to occurs frequently and is not only related to this event.  I am not able to assign any particular symptoms to the other occurrences of the error but I will definitively need to address this and see what could lead to this.

If you think it would be better to have this bug closed with a status similar to "Cannot reproduce", I would be OK. Let me know what you think.

**Comment by cwanja** [comment]
Honestly, not sure there is anything to be concerned with the `non-existing domain` error. In my container, logs dating back to mid-April, there were over 1000 instances in the logs. 
```
pi@teslapi:~/Documents/teslamate $ docker-compose logs teslamate | grep -c 'non-existing domain'
1140
```
Mostly being these two variations:
```
teslamate_1  | 2022-05-11 01:15:10.478 [error] GET https://owner-api.teslamotors.com/api/1/vehicles/[removed] -> error: "non-existing domain" (8012.088 ms)
teslamate_1  | 2022-05-11 01:15:10.478 [warning] TeslaApi.Error / non-existing domain
teslamate_1  | 2022-05-11 01:15:48.494 [error] GET https://owner-api.teslamotors.com/api/1/vehicles/[removed] -> error: "non-existing domain" (8011.905 ms)
teslamate_1  | 2022-05-11 01:15:48.494 [warning] TeslaApi.Error / non-existing domain
teslamate_1  | 2022-05-11 01:34:10.695 [error] POST https://auth.tesla.com/oauth2/v3/token -> error: "non-existing domain" (8010.124 ms)
teslamate_1  |   message: "non-existing domain",
```
Yet I have no issues with TeslaMate. Never missed a drive, charge, update, etc.
