### ISSUE TITLE
showing OFFLINE instead of ASLEEP

### ISSUE THREAD

**Issue by NasElMoro** [teslamate-org/teslamate#2907]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Since 01-04-2022 I noticed that my car is not showing the status 'ASLEEP' anymore. It's showing 'OFFLINE' whenever the car is seems to be sleeping although the car is connected to my home WIFI most of the time. From the point that the status is showing 'OFFLINE' is when my car was update to version 2022.8.3 coming from 2022.4.5.8. At this moment I'm running 2022.24.8 but the issue still persists.

I have a MX from late 2018.

### Expected Behavior

I expect that I see the status 'ASLEEP'  instead of 'OFFLINE'

### Relevant log output

```shell
dometer: 39531.0, power: 3, range: 56, shift_state: "R", soc: 18, speed: 0, time: ~U[2022-09-20 19:21:45.738Z]}
teslamate_1  | 2022-09-20 19:21:45.999 car_id=1 [info] Driving / Start
teslamate_1  | 2022-09-20 19:22:03.517 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/1492932307735693/vehicle_data -> 408 (76.021 ms)
teslamate_1  | 2022-09-20 19:22:04.759 car_id=1 [warning] Vehicle went offline while driving
teslamate_1  | 2022-09-20 19:22:05.300 car_id=1 [info] Fetch already in progress ...
teslamate_1  | 2022-09-20 19:22:05.540 car_id=1 [info] Fetch already in progress ...
teslamate_1  | 2022-09-20 19:22:05.800 car_id=1 [info] Fetch already in progress ...
teslamate_1  | 2022-09-20 19:22:06.300 car_id=1 [info] Fetch already in progress ...
teslamate_1  | 2022-09-20 19:22:06.539 car_id=1 [info] Fetch already in progress ...
teslamate_1  | 2022-09-20 19:22:06.661 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/1492932307735693/vehicle_data -> 408 (1860.687 ms)
teslamate_1  | 2022-09-20 19:22:06.888 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/1492932307735693/vehicle_data -> 408 (79.589 ms)
teslamate_1  | 2022-09-20 19:22:07.039 car_id=1 [info] Fetch already in progress ...
teslamate_1  | 2022-09-20 19:22:07.300 car_id=1 [info] Fetch already in progress ...
teslamate_1  | 2022-09-20 19:22:07.540 car_id=1 [info] Fetch already in progress ...
teslamate_1  | 2022-09-20 19:22:07.800 car_id=1 [info] Fetch already in progress ...
teslamate_1  | 2022-09-20 19:22:08.040 car_id=1 [info] Fetch already in progress ...
teslamate_1  | 2022-09-20 19:22:08.300 car_id=1 [info] Fetch already in progress ...
teslamate_1  | 2022-09-20 19:22:08.800 car_id=1 [info] Fetch already in progress ...
teslamate_1  | 2022-09-20 19:22:09.040 car_id=1 [info] Fetch already in progress ...
teslamate_1  | 2022-09-20 19:22:09.299 car_id=1 [info] Fetch already in progress ...
teslamate_1  | 2022-09-20 19:22:09.540 car_id=1 [info] Fetch already in progress ...
teslamate_1  | 2022-09-20 19:22:09.800 car_id=1 [info] Fetch already in progress ...
teslamate_1  | 2022-09-20 19:22:10.040 car_id=1 [info] Fetch already in progress ...
teslamate_1  | 2022-09-20 19:22:10.300 car_id=1 [info] Fetch already in progress ...
teslamate_1  | 2022-09-20 19:22:10.541 car_id=1 [info] Fetch already in progress ...
teslamate_1  | 2022-09-20 19:22:10.865 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/1492932307735693/vehicle_data -> 408 (76.043 ms)
teslamate_1  | 2022-09-20 19:22:11.115 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/1492932307735693/vehicle_data -> 408 (75.080 ms)
teslamate_1  | 2022-09-20 19:22:11.533 car_id=1 [info] Fetch already in progress ...
teslamate_1  | 2022-09-20 19:22:11.782 car_id=1 [info] Fetch already in progress ...
teslamate_1  | 2022-09-20 19:22:12.040 car_id=1 [info] Fetch already in progress ...
teslamate_1  | 2022-09-20 19:22:12.300 car_id=1 [info] Fetch already in progress ...
teslamate_1  | 2022-09-20 19:22:12.540 car_id=1 [info] Fetch already in progress ...
teslamate_1  | 2022-09-20 19:22:12.800 car_id=1 [info] Fetch already in progress ...
teslamate_1  | 2022-09-20 19:22:13.032 car_id=1 [info] Fetch already in progress ...
teslamate_1  | 2022-09-20 19:22:13.300 car_id=1 [info] Fetch already in progress ...
teslamate_1  | 2022-09-20 19:22:13.539 car_id=1 [info] Fetch already in progress ...
teslamate_1  | 2022-09-20 19:22:13.780 car_id=1 [info] Fetch already in progress ...
teslamate_1  | 2022-09-20 19:22:13.896 car_id=1 [info] Vehicle is back online
teslamate_1  | 2022-09-20 19:28:55.853 [info] GET https://nominatim.openstreetmap.org/reverse -> 200 (353.697 ms)
teslamate_1  | 2022-09-20 19:28:56.332 [info] GET https://nominatim.openstreetmap.org/reverse -> 200 (386.748 ms)
teslamate_1  | 2022-09-20 19:28:56.803 [info] End of drive initiated by: %TeslaApi.Vehicle.State.Drive{gps_as_of: 1663702102, heading: 310, latitude: 52.03811, longitude: 4.500311, native_latitude: 52.03811, native_location_supported: 1, native_longitude: 4.500311, native_type: "wgs", power: 2, shift_state: "P", speed: 0, timestamp: 1663702104059}
teslamate_1  | 2022-09-20 19:28:56.803 car_id=1 [info] Driving / Ended / 4 km – 7 min
teslamate_1  | 2022-09-20 19:28:56.803 car_id=1 [info] Start / :online
teslamate_1  | 2022-09-20 19:45:46.469 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/1492932307735693/vehicle_data -> 408 (10459.182 ms)
teslamate_1  | 2022-09-20 19:45:46.469 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-09-20 19:45:46.469 car_id=1 [error] Error / :unknown
teslamate_1  | 2022-09-20 19:46:38.912 car_id=1 [info] Suspending logging
teslamate_1  | 2022-09-20 20:16:50.005 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/1492932307735693/vehicle_data -> 408 (10857.895 ms)
teslamate_1  | 2022-09-20 20:16:50.005 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-09-20 20:16:50.005 car_id=1 [error] Error / :unknown
teslamate_1  | 2022-09-20 20:17:24.700 car_id=1 [info] Vehicle is still online. Falling asleep for: 34 min
teslamate_1  | 2022-09-20 20:47:34.082 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/1492932307735693/vehicle_data -> 408 (9087.888 ms)
teslamate_1  | 2022-09-20 20:47:34.082 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-09-20 20:47:34.082 car_id=1 [error] Error / :unknown
teslamate_1  | 2022-09-20 20:47:37.062 car_id=1 [info] Fetching vehicle state ...
teslamate_1  | 2022-09-20 20:48:13.246 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/1492932307735693/vehicle_data -> 408 (9096.257 ms)
teslamate_1  | 2022-09-20 20:48:13.246 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-09-20 20:48:13.246 car_id=1 [error] Error / :unknown
teslamate_1  | 2022-09-20 20:48:39.789 [error] Vehicle Error: Vehicle is offline
teslamate_1  | 2022-09-20 20:48:43.308 car_id=1 [info] Start / :offline
teslamate_1  | 2022-09-20 20:48:43.449 car_id=1 [info] Disconnecting ...
teslamate_1  | 2022-09-20 21:04:48.628 car_id=1 [info] Start / :online
teslamate_1  | 2022-09-20 21:04:48.715 car_id=1 [info] Connecting ...
teslamate_1  | 2022-09-20 21:04:48.716 [info] Start of drive initiated by: %TeslaApi.Vehicle.State.Drive{gps_as_of: 1663707886, heading: 307, latitude: 52.038113, longitude: 4.500308, native_latitude: 52.038113, native_location_supported: 1, native_longitude: 4.500308, native_type: "wgs", power: 2, shift_state: "R", speed: 1, timestamp: 1663707888541}
teslamate_1  | 2022-09-20 21:04:48.716 car_id=1 [info] Driving / Start
teslamate_1  | 2022-09-20 21:11:57.216 car_id=1 [info] Fetch already in progress ...
teslamate_1  | 2022-09-20 21:12:31.314 [info] GET https://nominatim.openstreetmap.org/reverse -> 200 (368.812 ms)
teslamate_1  | 2022-09-20 21:12:31.825 [info] GET https://nominatim.openstreetmap.org/reverse -> 200 (315.526 ms)
teslamate_1  | 2022-09-20 21:12:32.364 [info] End of drive initiated by: %TeslaApi.Vehicle.State.Drive{gps_as_of: 1663708316, heading: 66, latitude: 52.042817, longitude: 4.473455, native_latitude: 52.042817, native_location_supported: 1, native_longitude: 4.473455, native_type: "wgs", power: 1, shift_state: "P", speed: 0, timestamp: 1663708317361}
teslamate_1  | 2022-09-20 21:12:32.364 car_id=1 [info] Driving / Ended / 5 km – 7 min
teslamate_1  | 2022-09-20 21:12:32.364 car_id=1 [info] Start / :online
teslamate_1  | 2022-09-20 21:14:49.654 [info] GET https://nominatim.openstreetmap.org/reverse -> 200 (175.727 ms)
teslamate_1  | 2022-09-20 21:14:50.109 car_id=1 [info] Charging / SOC: 14%
teslamate_1  | 2022-09-20 21:14:50.110 car_id=1 [info] Disconnecting ...
teslamate_1  | 2022-09-20 21:14:50.111 car_id=1 [info] Received stream data: %TeslaApi.Stream.Data{elevation: -5, est_heading: 66, est_lat: 52.042817, est_lng: 4.473455, est_range: 32, heading: 66, odometer: 39536.3, power: -2, range: 45, shift_state: "P", soc: 14, speed: nil, time: ~U[2022-09-20 21:14:50.007Z]}
teslamate_1  | 2022-09-20 23:24:13.634 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/1492932307735693/vehicle_data -> 401 (36.170 ms)
teslamate_1  | 2022-09-20 23:24:13.844 car_id=1 [error] Error / :unauthorized
teslamate_1  | 2022-09-20 23:24:13.844 [info] Refreshing access token ...
teslamate_1  | 2022-09-20 23:24:14.214 [info] POST https://auth.tesla.com/oauth2/v3/token -> 200 (361.165 ms)
teslamate_1  | 2022-09-20 23:24:14.387 [info] Scheduling token refresh in 6 h
teslamate_1  | 2022-09-20 23:28:16.454 [warning] GET https://owner-api.teslamotors.com/api/1/vehicles/1492932307735693/vehicle_data -> 503 (65.350 ms)
teslamate_1  | 2022-09-20 23:28:16.454 [warning] TeslaApi.Error / GRPC::Unavailable: Socket closed
teslamate_1  | 2022-09-20 23:28:16.455 car_id=1 [error] Error / :unknown
teslamate_1  | 2022-09-21 00:02:03.008 [error] GenServer {Tortoise.Registry, {Tortoise.Connection, "TESLAMATE_302E3330373"}} terminating
teslamate_1  | ** (stop) :ping_timeout
teslamate_1  | Last message: :ping
teslamate_1  | 2022-09-21 00:02:04.089 [error] GenServer {Tortoise.Registry, {Tortoise.Connection.Supervisor, "TESLAMATE_302E3330373"}} terminating
teslamate_1  | ** (stop) :ping_timeout
teslamate_1  | Last message: {:EXIT, #PID<0.12019.28>, :ping_timeout}
teslamate_1  | 2022-09-21 00:02:14.366 [info] MQTT connection has been established
teslamate_1  | 2022-09-21 00:27:38.870 [warning] MQTT Client has been terminated with reason: {:function_clause, [{TeslaMate.Mqtt.Handler, :connection, [:terminated, []], [file: 'lib/teslamate/mqtt/handler.ex', line: 7]}, {Tortoise.Handler, :execute, 2, [file: 'lib/tortoise/handler.ex', line: 340]}, {Tortoise.Connection.Controller, :handle_info, 2, [file: 'lib/tortoise/connection/controller.ex', line: 215]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 695]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 771]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}
teslamate_1  | 2022-09-21 00:27:37.894 [error] GenServer {Tortoise.Registry, {Tortoise.Connection, "TESLAMATE_302E3330373"}} terminating
teslamate_1  | ** (stop) :ping_timeout
teslamate_1  | Last message: :ping
teslamate_1  | 2022-09-21 00:27:39.471 [error] GenServer {Tortoise.Registry, {Tortoise.Connection.Controller, "TESLAMATE_302E3330373"}} terminating
teslamate_1  | ** (FunctionClauseError) no function clause matching in TeslaMate.Mqtt.Handler.connection/2
teslamate_1  |     (teslamate 1.27.1) lib/teslamate/mqtt/handler.ex:7: TeslaMate.Mqtt.Handler.connection(:terminated, [])
teslamate_1  |     (tortoise 0.10.0) lib/tortoise/handler.ex:340: Tortoise.Handler.execute/2
teslamate_1  |     (tortoise 0.10.0) lib/tortoise/connection/controller.ex:215: Tortoise.Connection.Controller.handle_info/2
teslamate_1  |     (stdlib 3.17.2) gen_server.erl:695: :gen_server.try_dispatch/4
teslamate_1  |     (stdlib 3.17.2) gen_server.erl:771: :gen_server.handle_msg/6
teslamate_1  |     (stdlib 3.17.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
teslamate_1  | Last message: {{Tortoise, "TESLAMATE_302E3330373"}, :status, :terminated}
teslamate_1  | 2022-09-21 00:27:41.217 [error] GenServer {Tortoise.Registry, {Tortoise.Connection.Supervisor, "TESLAMATE_302E3330373"}} terminating
teslamate_1  | ** (stop) :ping_timeout
teslamate_1  | Last message: {:EXIT, #PID<0.19808.30>, :ping_timeout}
teslamate_1  | 2022-09-21 00:27:44.456 [info] MQTT connection has been established
teslamate_1  | 2022-09-21 04:08:39.243 car_id=1 [info] Derived efficiency factor: 216.0 Wh/km (31x confirmed)
teslamate_1  | 2022-09-21 04:08:39.348 car_id=1 [info] Charging / Complete / 59.42 kWh – 414 min
teslamate_1  | 2022-09-21 04:08:39.790 car_id=1 [info] Start / :online
teslamate_1  | 2022-09-21 04:08:40.045 car_id=1 [info] Connecting ...
teslamate_1  | 2022-09-21 04:11:45.529 car_id=1 [info] Suspending logging
teslamate_1  | 2022-09-21 04:20:59.597 car_id=1 [info] Fetching vehicle state ...
teslamate_1  | 2022-09-21 04:21:31.411 [error] Vehicle Error: Vehicle is offline
teslamate_1  | 2022-09-21 04:22:02.767 [error] Vehicle Error: Vehicle is offline
teslamate_1  | 2022-09-21 04:22:34.283 [error] Vehicle Error: Vehicle is offline
teslamate_1  | 2022-09-21 04:23:04.987 [error] Vehicle Error: Vehicle is offline
teslamate_1  | 2022-09-21 04:23:35.310 [error] Vehicle Error: Vehicle is offline
teslamate_1  | 2022-09-21 04:24:05.612 [error] Vehicle Error: Vehicle is offline
teslamate_1  | 2022-09-21 04:24:35.899 [error] Vehicle Error: Vehicle is offline
teslamate_1  | 2022-09-21 04:25:07.017 [error] Vehicle Error: Vehicle is offline
teslamate_1  | 2022-09-21 04:25:38.966 [error] Vehicle Error: Vehicle is offline
teslamate_1  | 2022-09-21 04:26:08.966 car_id=1 [info] Fetching vehicle state ...
teslamate_1  | 2022-09-21 04:26:09.185 car_id=1 [info] Start / :offline
teslamate_1  | 2022-09-21 04:26:09.314 [error] Vehicle Error: Vehicle is offline
teslamate_1  | 2022-09-21 04:26:09.422 car_id=1 [info] Disconnecting ...
teslamate_1  | 2022-09-21 04:29:59.834 [info] GET /
teslamate_1  | 2022-09-21 04:29:59.944 [info] Sent 200 in 109ms
teslamate_1  | waiting for postgres at database:5432
teslamate_1  | waiting for postgres at database:5432
teslamate_1  | waiting for postgres at database:5432
teslamate_1  | waiting for postgres at database:5432
teslamate_1  | 2022-09-21 05:32:16.457 [info] Migrations already up
teslamate_1  | 2022-09-21 05:32:21.702 [info] System Info: Erlang/OTP 24 (jit)
teslamate_1  | 2022-09-21 05:32:21.702 [info] Version: 1.27.1
teslamate_1  | 2022-09-21 05:32:22.355 [info] POST https://auth.tesla.com/oauth2/v3/token -> 200 (352.852 ms)
teslamate_1  | 2022-09-21 05:32:22.355 [info] Refreshed api tokens
teslamate_1  | 2022-09-21 05:32:22.478 [info] Scheduling token refresh in 6 h
teslamate_1  | 2022-09-21 05:32:22.483 [info] Running TeslaMateWeb.Endpoint with cowboy 2.9.0 at :::4000 (http)
teslamate_1  | 2022-09-21 05:32:22.521 [info] Access TeslaMateWeb.Endpoint at http://192.168.1.173
teslamate_1  | 2022-09-21 05:32:24.976 [info] Starting logger for 'Nas El Moro'
teslamate_1  | 2022-09-21 05:32:25.997 [info] MQTT connection has been established
teslamate_1  | 2022-09-21 05:32:29.246 car_id=1 [info] Start / :online
teslamate_1  | 2022-09-21 05:32:31.927 car_id=1 [info] Connecting ...
teslamate_1  | 2022-09-21 05:32:31.928 [info] Start of drive initiated by: %TeslaApi.Vehicle.State.Drive{gps_as_of: 1663738348, heading: 73, latitude: 52.07074, longitude: 4.900816, native_latitude: 52.07074, native_location_supported: 1, native_longitude: 4.900816, native_type: "wgs", power: 22, shift_state: "D", speed: 59, timestamp: 1663738349454}
teslamate_1  | 2022-09-21 05:32:31.929 car_id=1 [info] Driving / Start
teslamate_1  | 2022-09-21 05:55:51.185 [info] GET https://nominatim.openstreetmap.org/reverse -> 200 (731.110 ms)
teslamate_1  | 2022-09-21 05:55:52.124 [info] GET https://nominatim.openstreetmap.org/reverse -> 200 (118.525 ms)
teslamate_1  | 2022-09-21 05:55:52.574 [info] End of drive initiated by: %TeslaApi.Vehicle.State.Drive{gps_as_of: 1663739714, heading: 232, latitude: 52.094796, longitude: 5.140727, native_latitude: 52.094796, native_location_supported: 1, native_longitude: 5.140727, native_type: "wgs", power: 3, shift_state: "P", speed: 0, timestamp: 1663739716049}
teslamate_1  | 2022-09-21 05:55:52.574 car_id=1 [info] Driving / Ended / 22 km – 23 min
teslamate_1  | 2022-09-21 05:55:52.574 car_id=1 [info] Start / :online
teslamate_1  | 2022-09-21 05:59:04.799 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/1492932307735693/vehicle_data -> 408 (9828.069 ms)
teslamate_1  | 2022-09-21 05:59:04.799 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-09-21 05:59:04.799 car_id=1 [error] Error / :unknown
teslamate_1  | 2022-09-21 05:59:36.181 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/1492932307735693/vehicle_data -> 408 (11380.867 ms)
teslamate_1  | 2022-09-21 05:59:36.182 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-09-21 05:59:36.182 car_id=1 [error] Error / :unknown
teslamate_1  | 2022-09-21 06:00:00.929 car_id=1 [info] Suspending logging
teslamate_1  | 2022-09-21 06:03:39.070 car_id=1 [info] Fetching vehicle state ...
teslamate_1  | 2022-09-21 06:04:43.291 [error] Vehicle Error: Vehicle is offline
teslamate_1  | 2022-09-21 06:05:13.611 [error] Vehicle Error: Vehicle is offline
teslamate_1  | 2022-09-21 06:05:44.421 [error] Vehicle Error: Vehicle is offline
teslamate_1  | 2022-09-21 06:06:14.732 [error] Vehicle Error: Vehicle is offline
teslamate_1  | 2022-09-21 06:06:45.042 [error] Vehicle Error: Vehicle is offline
teslamate_1  | 2022-09-21 06:07:16.652 [error] Vehicle Error: Vehicle is offline
teslamate_1  | 2022-09-21 06:07:55.420 [error] Vehicle Error: Vehicle is offline
teslamate_1  | 2022-09-21 06:08:26.388 [error] Vehicle Error: Vehicle is offline
teslamate_1  | 2022-09-21 06:08:56.388 car_id=1 [info] Fetching vehicle state ...
teslamate_1  | 2022-09-21 06:08:56.760 [error] Vehicle Error: Vehicle is offline
teslamate_1  | 2022-09-21 06:08:57.806 car_id=1 [info] Start / :offline
teslamate_1  | 2022-09-21 06:08:58.358 car_id=1 [info] Disconnecting ...
teslamate_1  | 2022-09-21 06:13:45.237 [info] GET /
teslamate_1  | 2022-09-21 06:13:46.206 [info] Sent 200 in 968ms
teslamate_1  | 2022-09-21 06:13:50.678 [info] GET /settings
teslamate_1  | 2022-09-21 06:13:50.903 [info] Sent 200 in 224ms
teslamate_1  | 2022-09-21 08:34:33.599 car_id=1 [info] Start / :online
teslamate_1  | 2022-09-21 08:34:34.872 car_id=1 [info] Connecting ...
teslamate_1  | 2022-09-21 08:37:42.076 car_id=1 [info] Suspending logging
teslamate_1  | 2022-09-21 09:07:45.527 car_id=1 [info] Vehicle is still online. Falling asleep for: 33 min
teslamate_1  | 2022-09-21 09:37:47.419 car_id=1 [info] Vehicle is still online. Falling asleep for: 1 h 3 min
teslamate_1  | 2022-09-21 10:07:58.570 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/1492932307735693/vehicle_data -> 408 (9073.779 ms)
teslamate_1  | 2022-09-21 10:07:58.608 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-09-21 10:07:58.609 car_id=1 [error] Error / :unknown
teslamate_1  | 2022-09-21 10:08:28.955 car_id=1 [info] Vehicle is still online. Falling asleep for: 1 h 33 min
teslamate_1  | 2022-09-21 10:12:15.800 car_id=1 [info] Fetching vehicle state ...
teslamate_1  | 2022-09-21 10:12:46.498 [error] Vehicle Error: Vehicle is offline
teslamate_1  | 2022-09-21 10:13:16.837 [error] Vehicle Error: Vehicle is offline
teslamate_1  | 2022-09-21 10:13:47.157 [error] Vehicle Error: Vehicle is offline
teslamate_1  | 2022-09-21 10:14:20.615 [error] Vehicle Error: Vehicle is offline
teslamate_1  | 2022-09-21 10:14:52.704 [error] Vehicle Error: Vehicle is offline
```

### Screenshots

<img width="1598" alt="Schermafbeelding 2022-09-21 om 11 40 02" src="https://user-images.githubusercontent.com/62408621/191472818-0e8f6403-0159-48c4-b5f5-172f96c15603.png">

### Type of installation

Docker

### Version

v1.27.1

**Comment by sultantariq** [comment]
I was having the same issue and fixed it by rebooting the car once or twice.

**Comment by NasElMoro** [comment]
> I was having the same issue and fixed it by rebooting the car once or twice.

Do you also have a MX? Which steps did you execute to  ‘reboot’ your car?

**Comment by eden881** [comment]
I have the same issue, it started after updating from 2022.28.2 to 2022.36.5.
However the car did show up as 'ASLEEP' several times after the update. It only started to show 'OFFLINE' after I charged the car overnight.

<img width="1920" alt="1" src="https://user-images.githubusercontent.com/21142645/197473440-922da1e0-3a1e-4dbb-b6dd-052c210c8792.png">
