### ISSUE TITLE
v1.27 Status unavailable in China

### ISSUE THREAD

**Issue by Asuna00412** [teslamate-org/teslamate#2933]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

This is China, the mode3 made in China. After I install the container, the container runs correct. But after my first trip, the Teslamate shows 'Status | unavailable'. I install the container step by step from the index page.

### Relevant log output

```shell
teslamate_1  | 2022-10-07 13:00:18.522 car_id=1 [info] Start / :online
teslamate_1  | 2022-10-07 13:00:18.527 [error] GenStateMachine :"1" terminating
teslamate_1  | ** (MatchError) no match of right hand side value: {:error, #Ecto.Changeset<action: :update, changes: %{end_date: ~U[2022-10-07 05:00:18.812000Z]}, errors: [end_date: {"end date must be after start date", [constraint: :check, constraint_name: "positive_duration"]}], data: #TeslaMate.Log.State<>, valid?: false>}
teslamate_1  |     (teslamate 1.27.1) lib/teslamate/vehicles/vehicle.ex:716: anonymous fn/4 in TeslaMate.Vehicles.Vehicle.handle_event/4
teslamate_1  |     (ecto_sql 3.8.3) lib/ecto/adapters/sql.ex:1222: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
teslamate_1  |     (db_connection 2.4.2) lib/db_connection.ex:1562: DBConnection.run_transaction/4
teslamate_1  |     (teslamate 1.27.1) lib/teslamate/vehicles/vehicle.ex:711: TeslaMate.Vehicles.Vehicle.handle_event/4
teslamate_1  |     (stdlib 3.17.2) gen_statem.erl:1205: :gen_statem.loop_state_callback/11
teslamate_1  |     (stdlib 3.17.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
teslamate_1  | 2022-10-07 13:00:18.962 car_id=1 [info] Start / :online
teslamate_1  | 2022-10-07 13:00:18.967 [error] GenStateMachine :"1" terminating
teslamate_1  | ** (MatchError) no match of right hand side value: {:error, #Ecto.Changeset<action: :update, changes: %{end_date: ~U[2022-10-07 05:00:19.269000Z]}, errors: [end_date: {"end date must be after start date", [constraint: :check, constraint_name: "positive_duration"]}], data: #TeslaMate.Log.State<>, valid?: false>}
teslamate_1  |     (teslamate 1.27.1) lib/teslamate/vehicles/vehicle.ex:716: anonymous fn/4 in TeslaMate.Vehicles.Vehicle.handle_event/4
teslamate_1  |     (ecto_sql 3.8.3) lib/ecto/adapters/sql.ex:1222: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
teslamate_1  |     (db_connection 2.4.2) lib/db_connection.ex:1562: DBConnection.run_transaction/4
teslamate_1  |     (teslamate 1.27.1) lib/teslamate/vehicles/vehicle.ex:711: TeslaMate.Vehicles.Vehicle.handle_event/4
teslamate_1  |     (stdlib 3.17.2) gen_statem.erl:1205: :gen_statem.loop_state_callback/11
teslamate_1  |     (stdlib 3.17.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
teslamate_1  | 2022-10-07 13:00:19.419 car_id=1 [info] Start / :online
teslamate_1  | 2022-10-07 13:00:19.424 [error] GenStateMachine :"1" terminating
teslamate_1  | ** (MatchError) no match of right hand side value: {:error, #Ecto.Changeset<action: :update, changes: %{end_date: ~U[2022-10-07 05:00:19.725000Z]}, errors: [end_date: {"end date must be after start date", [constraint: :check, constraint_name: "positive_duration"]}], data: #TeslaMate.Log.State<>, valid?: false>}
teslamate_1  |     (teslamate 1.27.1) lib/teslamate/vehicles/vehicle.ex:716: anonymous fn/4 in TeslaMate.Vehicles.Vehicle.handle_event/4
teslamate_1  |     (ecto_sql 3.8.3) lib/ecto/adapters/sql.ex:1222: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
teslamate_1  |     (db_connection 2.4.2) lib/db_connection.ex:1562: DBConnection.run_transaction/4
teslamate_1  |     (teslamate 1.27.1) lib/teslamate/vehicles/vehicle.ex:711: TeslaMate.Vehicles.Vehicle.handle_event/4
teslamate_1  |     (stdlib 3.17.2) gen_statem.erl:1205: :gen_statem.loop_state_callback/11
teslamate_1  |     (stdlib 3.17.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
teslamate_1  | 2022-10-07 13:00:19.851 car_id=1 [info] Start / :online
teslamate_1  | 2022-10-07 13:00:19.856 [error] GenStateMachine :"1" terminating
teslamate_1  | ** (MatchError) no match of right hand side value: {:error, #Ecto.Changeset<action: :update, changes: %{end_date: ~U[2022-10-07 05:00:20.158000Z]}, errors: [end_date: {"end date must be after start date", [constraint: :check, constraint_name: "positive_duration"]}], data: #TeslaMate.Log.State<>, valid?: false>}
teslamate_1  |     (teslamate 1.27.1) lib/teslamate/vehicles/vehicle.ex:716: anonymous fn/4 in TeslaMate.Vehicles.Vehicle.handle_event/4
teslamate_1  |     (ecto_sql 3.8.3) lib/ecto/adapters/sql.ex:1222: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
teslamate_1  |     (db_connection 2.4.2) lib/db_connection.ex:1562: DBConnection.run_transaction/4
teslamate_1  |     (teslamate 1.27.1) lib/teslamate/vehicles/vehicle.ex:711: TeslaMate.Vehicles.Vehicle.handle_event/4
teslamate_1  |     (stdlib 3.17.2) gen_statem.erl:1205: :gen_statem.loop_state_callback/11
teslamate_1  |     (stdlib 3.17.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
teslamate_1  | 2022-10-07 13:00:20.315 [info] Starting logger for '小黑'
teslamate_1  | 2022-10-07 13:00:20.768 car_id=1 [info] Start / :online
teslamate_1  | 2022-10-07 13:00:20.773 [error] GenStateMachine :"1" terminating
teslamate_1  | ** (MatchError) no match of right hand side value: {:error, #Ecto.Changeset<action: :update, changes: %{end_date: ~U[2022-10-07 05:00:21.082000Z]}, errors: [end_date: {"end date must be after start date", [constraint: :check, constraint_name: "positive_duration"]}], data: #TeslaMate.Log.State<>, valid?: false>}
teslamate_1  |     (teslamate 1.27.1) lib/teslamate/vehicles/vehicle.ex:716: anonymous fn/4 in TeslaMate.Vehicles.Vehicle.handle_event/4
teslamate_1  |     (ecto_sql 3.8.3) lib/ecto/adapters/sql.ex:1222: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
teslamate_1  |     (db_connection 2.4.2) lib/db_connection.ex:1562: DBConnection.run_transaction/4
teslamate_1  |     (teslamate 1.27.1) lib/teslamate/vehicles/vehicle.ex:711: TeslaMate.Vehicles.Vehicle.handle_event/4
teslamate_1  |     (stdlib 3.17.2) gen_statem.erl:1205: :gen_statem.loop_state_callback/11
teslamate_1  |     (stdlib 3.17.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
teslamate_1  | 2022-10-07 13:00:21.073 car_id=1 [warning] Error / unknown vehicle state "unknown"
teslamate_1  | 
teslamate_1  | %TeslaApi.Vehicle{
teslamate_1  |   api_version: nil,
teslamate_1  |   backseat_token: nil,
teslamate_1  |   backseat_token_updated_at: nil,
teslamate_1  |   calendar_enabled: nil,
teslamate_1  |   charge_state: nil,
teslamate_1  |   climate_state: nil,
teslamate_1  |   color: nil,
teslamate_1  |   display_name: nil,
teslamate_1  |   drive_state: nil,
teslamate_1  |   gui_settings: nil,
teslamate_1  |   id: nil,
teslamate_1  |   in_service: nil,
teslamate_1  |   option_codes: [""],
teslamate_1  |   state: "unknown",
teslamate_1  |   tokens: nil,
teslamate_1  |   vehicle_config: nil,
teslamate_1  |   vehicle_id: nil,
teslamate_1  |   vehicle_state: nil,
teslamate_1  |   vin: nil
teslamate_1  | }
teslamate_1  | 2022-10-07 13:00:31.517 car_id=1 [info] Start / :online
teslamate_1  | 2022-10-07 13:00:31.523 [error] GenStateMachine :"1" terminating
teslamate_1  | ** (MatchError) no match of right hand side value: {:error, #Ecto.Changeset<action: :update, changes: %{end_date: ~U[2022-10-07 05:00:31.823000Z]}, errors: [end_date: {"end date must be after start date", [constraint: :check, constraint_name: "positive_duration"]}], data: #TeslaMate.Log.State<>, valid?: false>}
teslamate_1  |     (teslamate 1.27.1) lib/teslamate/vehicles/vehicle.ex:716: anonymous fn/4 in TeslaMate.Vehicles.Vehicle.handle_event/4
teslamate_1  |     (ecto_sql 3.8.3) lib/ecto/adapters/sql.ex:1222: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
teslamate_1  |     (db_connection 2.4.2) lib/db_connection.ex:1562: DBConnection.run_transaction/4
teslamate_1  |     (teslamate 1.27.1) lib/teslamate/vehicles/vehicle.ex:711: TeslaMate.Vehicles.Vehicle.handle_event/4
teslamate_1  |     (stdlib 3.17.2) gen_statem.erl:1205: :gen_statem.loop_state_callback/11
teslamate_1  |     (stdlib 3.17.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
teslamate_1  | 2022-10-07 13:00:32.018 car_id=1 [info] Start / :online
teslamate_1  | 2022-10-07 13:00:32.023 [error] GenStateMachine :"1" terminating
teslamate_1  | ** (MatchError) no match of right hand side value: {:error, #Ecto.Changeset<action: :update, changes: %{end_date: ~U[2022-10-07 05:00:32.323000Z]}, errors: [end_date: {"end date must be after start date", [constraint: :check, constraint_name: "positive_duration"]}], data: #TeslaMate.Log.State<>, valid?: false>}
teslamate_1  |     (teslamate 1.27.1) lib/teslamate/vehicles/vehicle.ex:716: anonymous fn/4 in TeslaMate.Vehicles.Vehicle.handle_event/4
teslamate_1  |     (ecto_sql 3.8.3) lib/ecto/adapters/sql.ex:1222: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
teslamate_1  |     (db_connection 2.4.2) lib/db_connection.ex:1562: DBConnection.run_transaction/4
teslamate_1  |     (teslamate 1.27.1) lib/teslamate/vehicles/vehicle.ex:711: TeslaMate.Vehicles.Vehicle.handle_event/4
teslamate_1  |     (stdlib 3.17.2) gen_statem.erl:1205: :gen_statem.loop_state_callback/11
teslamate_1  |     (stdlib 3.17.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
teslamate_1  | 2022-10-07 13:00:32.587 car_id=1 [info] Start / :online
teslamate_1  | 2022-10-07 13:00:32.592 [error] GenStateMachine :"1" terminating
```

### Screenshots

<img width="977" alt="2022-10-06 21 46 45" src="https://user-images.githubusercontent.com/91128344/194471695-88d16aaf-1d45-4810-8b3e-d0b8dc13b285.png">
<img width="992" alt="2022-10-07 13 05 25" src="https://user-images.githubusercontent.com/91128344/194471856-336a791e-6df9-4389-8a23-c267056520e8.png">
<img width="1574" alt="2022-10-07 13 05 49" src="https://user-images.githubusercontent.com/91128344/194471866-bf98ddf5-4732-4c9c-8f26-94803a8d87cd.png">

### Type of installation

Docker

### Version

v1.27

**Comment by Asuna00412** [comment]
version: "3"

services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    environment:
      - ENCRYPTION_KEY=my#encryption&secret
      - DATABASE_USER=teslamate
      - DATABASE_PASS=My#db&secret
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
    ports:
      - 4000:4000
    volumes:
      - ./import:/opt/app/import
    cap_drop:
      - all

  database:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=My#db&secret
      - POSTGRES_DB=teslamate
    volumes:
      - teslamate-db:/var/lib/postgresql/data

  grafana:
    image: teslamate/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=My#db&secret
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
    ports:
      - 3000:3000
    volumes:
      - teslamate-grafana-data:/var/lib/grafana

  mosquitto:
    image: eclipse-mosquitto:2
    restart: always
    command: mosquitto -c /mosquitto-no-auth.conf
    # ports:
    #   - 1883:1883
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

volumes:
  teslamate-db:
  teslamate-grafana-data:
  mosquitto-conf:
  mosquitto-data:

**Comment by Asudy** [comment]
Did you upgraded from v1.26 or directly installed v1.27 recently? I'm in 1.26 now preparing to upgrade. Seems like I'd better wait if v1.27 is causing this issue. 😢

**Comment by Asuna00412** [comment]
Yes, of course.> Did you get a cellular signal in your car?

**Comment by Asuna00412** [comment]
I directly installed v1.27. > Did you upgraded from v1.26 or directly installed v1.27 recently? I'm in 1.26 now preparing to upgrade. Seems like I'd better wait if v1.27 is causing this issue. 😢

**Comment by wuhan321** [comment]
兄弟，借个楼，问下，为啥我安装完也登录到grafana上了，就是看不到数据

**Comment by minggushen** [comment]
> 兄弟，借个楼，问下，为啥我安装完也登录到grafana上了，就是看不到数据

端口4000的那个token都填了吧

**Comment by wuhan321** [comment]
填了、日志报408

**Comment by wuhan321** [comment]
ok了,已自行查找到原因

**Comment by minggushen** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by nderooij** [comment]
> 这是来自QQ邮箱的假期自动回复邮件。   您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

Can you share what ended up being the fix?

**Comment by minggushen** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by minggushen** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
