### ISSUE TITLE
Encryption key containing a forward slash, entire installation destroyed

### ISSUE THREAD

**Issue by ndxyz00** [teslamate-org/teslamate#3005]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi,

I'm not exactly sure what happened but I will provide my interpretation of the events.

- I copied the random encryption key in the docker log
   (just to do things right, since nowhere is specified what type of key is required)
- pasted it into the .env
  Unfortunately I didn't realise that it contained a forward slash
  (i don't know the exact syntax used but the color of following strings changed... maybe?)
 At the same time left the tm password empty (deleted the string) and put the actual grafana user and password instead of admin that I created before in the web interface (but not sure this affected the issue)
- did the docker pull and up

After this, my installation on a docker on google cloud is corrupted and doesn't work in any form:
- from the web address you get 404, or an endless loop in safari searching for a certificate
- from the console docker log nothing is working anymore, it says the database doesn't exist and suggest using the command "mix ecto.create" to fix, but of course no such command is recognized.

I tried pasting back the .env and do the up but nothing works anymore...

What can I do now?
Can I at least recover the data n restore it into a new installation?
I didn't had a backup and now I'm uber fucked.

Thanx

PS the instructions on the .env strings really could be improved, what is what is left the the reader imagination just too much imho

### Relevant log output

```shell
teslamate_1  | 2022-12-02 01:24:40.502 [error] Postgrex.Protocol (#PID<0.165.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"
teslamate_1  | 2022-12-02 01:24:40.502 [error] Postgrex.Protocol (#PID<0.166.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"
teslamate_1  | 2022-12-02 01:24:42.762 [error] Postgrex.Protocol (#PID<0.166.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"
teslamate_1  | 2022-12-02 01:24:43.360 [error] Postgrex.Protocol (#PID<0.165.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"
teslamate_1  | 2022-12-02 01:24:43.456 [error] Could not create schema migrations table. This error usually happens due to the following:
teslamate_1  |
teslamate_1  |   * The database does not exist
teslamate_1  |   * The "schema_migrations" table, which Ecto uses for managing
teslamate_1  |     migrations, was defined by another library
teslamate_1  |   * There is a deadlock while migrating (such as using concurrent
teslamate_1  |     indexes with a migration_lock)
teslamate_1  |
teslamate_1  | To fix the first issue, run "mix ecto.create".
teslamate_1  |
teslamate_1  | To address the second, you can run "mix ecto.drop" followed by
teslamate_1  | "mix ecto.create". Alternatively you may configure Ecto to use
teslamate_1  | another table and/or repository for managing migrations:
teslamate_1  |
teslamate_1  |     config :teslamate, TeslaMate.Repo,
teslamate_1  |       migration_source: "some_other_table_for_schema_migrations",
teslamate_1  |       migration_repo: AnotherRepoForSchemaMigrations
teslamate_1  |
teslamate_1  | The full error report is shown below.
teslamate_1  |
teslamate_1  | ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2972ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
teslamate_1  |
teslamate_1  |   1. Ensuring your database is available and that you can connect to it
teslamate_1  |   2. Tracking down slow queries and making sure they are running fast enough
teslamate_1  |   3. Increasing the pool_size (although this increases resource consumption)
teslamate_1  |   4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
teslamate_1  |
teslamate_1  | See DBConnection.start_link/2 for more information
teslamate_1  |
teslamate_1  |     (ecto_sql 3.8.3) lib/ecto/adapters/sql.ex:932: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate_1  |     (elixir 1.13.4) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
teslamate_1  |     (ecto_sql 3.8.3) lib/ecto/adapters/sql.ex:1024: Ecto.Adapters.SQL.execute_ddl/4
teslamate_1  |     (ecto_sql 3.8.3) lib/ecto/migrator.ex:696: Ecto.Migrator.verbose_schema_migration/3
teslamate_1  |     (ecto_sql 3.8.3) lib/ecto/migrator.ex:510: Ecto.Migrator.lock_for_migrations/4
teslamate_1  |     (ecto_sql 3.8.3) lib/ecto/migrator.ex:422: Ecto.Migrator.run/4
teslamate_1  |     (ecto_sql 3.8.3) lib/ecto/migrator.ex:146: Ecto.Migrator.with_repo/3
teslamate_1  |     (teslamate 1.27.1) lib/teslamate/release.ex:9: anonymous fn/2 in TeslaMate.Release.migrate/0
teslamate_1  | 2022-12-02 01:24:45.546 [error] Postgrex.Protocol (#PID<0.166.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"
teslamate_1  | 2022-12-02 01:24:45.546 [error] Postgrex.Protocol (#PID<0.165.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"
teslamate_1  | 2022-12-02 01:24:47.327 [error] Postgrex.Protocol (#PID<0.166.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"
teslamate_1  | 2022-12-02 01:24:48.317 [error] Postgrex.Protocol (#PID<0.165.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"
teslamate_1  | 2022-12-02 01:24:48.501 [error] Could not create schema migrations table. This error usually happens due to the following:
```

### Type of installation

Docker

### Version

latest

**Comment by dyxyl** [comment]
I don't think a forward slash will cause any problems. The syntax of the .env is just lines of the form variable=value.

Do you have the wrong value for TM_DB_PASS in the .env?  That would cause the password authentication failed errors.  It should be set to the value that you used when you created the database initially.
