### ISSUE TITLE
Plugin Crashed my Grafana

### ISSUE THREAD

**Issue by prussell69** [teslamate-org/teslamate#3060]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I had added in the data source for my Powerwall Dashboard so I could see both systems from the same Grafana viewer. I added the  Influxdb and pointed to my server, added Sun and Moon (for weather info), then imported the "Powerwall Dashboard". It had been running just fine for several months, up until 2 days ago. After a reboot from a windows update the Grafana module in my Teslamate Docker, kept restarting and then failed. I tried to "Re-install" the Teslamate system, but it didn't correct the Grafana issue. I ran a backup on my original Teslamate, to recover my data. I then created a new Teslamate install folder called "Teslamate2". I ran the install and it created a Telsamate2 in docker. I had to stop my original Teslamate 1st.
It started just fine, so I imported my data.
I started to add in my Powerwall Dashboard info again, and it crashed again. I tried a 3rd, then 4th time, not adding the Powerwall the 4th time so I could keep my system running.
On another PC, I created a Teslamate, and a Powerwall Dashboard., and started again to find out the actual cause.

I added the Influx database - No Issue after restarting Docker.
I imported and added the Sun and Moon database - No Issue after restarting Docker.
I imported the dashboard - No Issue after restarting Docker (although one of the panels was missing it's plugin).
I imported the missing plugin: "Boom Table" - Grafana crashed!

I don't know why it crashed now, but didn't when I did this the first time months ago, but I tracked it down to when I added that plugin. I don't know how to remove that plugin from my Grafana, since it won't restart.
These are installed on Windows machines, and I'm not very savy at which command line to use for what (e.g. Windows cmd, git bash, wsl cmd). so any help would be greatly appreciated. I Loved having my Powerwall & Teslamate data on the same screen, and not having to "login" to which ever Grafana system I wanted to see.
Hopefully someone else has ran into this problem and can help. I saved the error log from Grafan if needed.

Please help...

### Expected Behavior

System was running with this setup prior to 2 days ago. I'm not sure why this happened now??? 

### Steps To Reproduce

1. Added Plugin: Boom Table
2. Crash!!!

### Relevant log output

```shell
2023-01-11 18:23:13 logger=settings t=2023-01-11T23:23:13.72+0000 lvl=info msg="Starting Grafana" version=8.5.6 commit=623255cf2d branch=HEAD compiled=2022-06-14T09:25:38Z
2023-01-11 18:23:13 logger=settings t=2023-01-11T23:23:13.72+0000 lvl=info msg="The state of unified alerting is still not defined. The decision will be made during as we run the database migrations"
2023-01-11 18:23:13 logger=settings t=2023-01-11T23:23:13.72+0000 lvl=info msg="Config loaded from" file=/usr/share/grafana/conf/defaults.ini
2023-01-11 18:23:13 logger=settings t=2023-01-11T23:23:13.72+0000 lvl=info msg="Config loaded from" file=/etc/grafana/grafana.ini
2023-01-11 18:23:13 logger=settings t=2023-01-11T23:23:13.72+0000 lvl=info msg="Config overridden from command line" arg="default.paths.data=/var/lib/grafana"
2023-01-11 18:23:13 logger=settings t=2023-01-11T23:23:13.72+0000 lvl=info msg="Config overridden from command line" arg="default.paths.logs=/var/log/grafana"
2023-01-11 18:23:13 logger=settings t=2023-01-11T23:23:13.72+0000 lvl=info msg="Config overridden from command line" arg="default.paths.plugins=/var/lib/grafana-plugins"
2023-01-11 18:23:13 logger=settings t=2023-01-11T23:23:13.72+0000 lvl=info msg="Config overridden from command line" arg="default.paths.provisioning=/etc/grafana/provisioning"
2023-01-11 18:23:13 panic: Grafana has already been migrated to Unified Alerting.
2023-01-11 18:23:13 Any alert rules created while using Unified Alerting will be deleted by rolling back.
2023-01-11 18:23:13 
2023-01-11 18:23:13 Set force_migration=true in your grafana.ini and restart Grafana to roll back and delete Unified Alerting configuration data.
2023-01-11 18:23:13 
2023-01-11 18:23:13 goroutine 1 [running]:
2023-01-11 18:23:13 github.com/grafana/grafana/pkg/services/sqlstore/migrations/ualert.AddDashAlertMigration(0xc000e2efa0)
2023-01-11 18:23:13 /drone/src/pkg/services/sqlstore/migrations/ualert/ualert.go:78 +0x797
2023-01-11 18:23:13 github.com/grafana/grafana/pkg/services/sqlstore/migrations.(*OSSMigrations).AddMigration(0xc000ec80e0, 0xc000e2efa0)
2023-01-11 18:23:13 /drone/src/pkg/services/sqlstore/migrations/migrations.go:61 +0x265
2023-01-11 18:23:13 github.com/grafana/grafana/pkg/services/sqlstore.(*SQLStore).Migrate(0xc000138600, 0x0)
2023-01-11 18:23:13 /drone/src/pkg/services/sqlstore/sqlstore.go:135 +0x6f
2023-01-11 18:23:13 github.com/grafana/grafana/pkg/services/sqlstore.ProvideService(0xc000cfc900, 0x18, {0x36f2100, 0x5763858}, {0x3717c40, 0xc000e2ebe0})
2023-01-11 18:23:13 /drone/src/pkg/services/sqlstore/sqlstore.go:67 +0xdc
2023-01-11 18:23:13 github.com/grafana/grafana/pkg/server.Initialize({{0x7fff800aeb5a, 0x18}, {0x7fff800aeb3e, 0x12}, {0xc0001a4040, 0x5, 0x5}}, {{0x0, 0x0}, {0x0, ...}, ...}, ...)
2023-01-11 18:23:13 /drone/src/pkg/server/wire_gen.go:148 +0x1b6
2023-01-11 18:23:13 github.com/grafana/grafana/pkg/cmd/grafana-server/commands.executeServer({0x7fff800aeb5a, 0x18}, {0x7fff800aeb3e, 0x12}, {0x0, 0x0}, {0x7fff800aeb7f, 0x6}, 0x0, {{0x3673580, ...}, ...})
2023-01-11 18:23:13 /drone/src/pkg/cmd/grafana-server/commands/cli.go:170 +0x625
2023-01-11 18:23:13 github.com/grafana/grafana/pkg/cmd/grafana-server/commands.RunServer({{0x3673580, 0x5}, {0x3674ed8, 0xa}, {0x3673578, 0x4}, {0x3674ec8, 0xa}})
2023-01-11 18:23:13 /drone/src/pkg/cmd/grafana-server/commands/cli.go:107 +0x785
2023-01-11 18:23:13 main.main()
2023-01-11 18:23:13 /drone/src/pkg/cmd/grafana-server/main.go:16 +0xc5
2023-01-11 18:23:14 panic: Grafana has already been migrated to Unified Alerting.
2023-01-11 18:23:14 Any alert rules created while using Unified Alerting will be deleted by rolling back.
2023-01-11 18:23:14 
2023-01-11 18:23:14 Set force_migration=true in your grafana.ini and restart Grafana to roll back and delete Unified Alerting configuration data.
2023-01-11 18:23:13 logger=settings t=2023-01-11T23:23:13.72+0000 lvl=info msg="Config overridden from command line" arg="default.log.mode=console"
2023-01-11 18:23:13 logger=settings t=2023-01-11T23:23:13.72+0000 lvl=info msg="Config overridden from Environment variable" var="GF_PATHS_DATA=/var/lib/grafana"
2023-01-11 18:23:13 logger=settings t=2023-01-11T23:23:13.72+0000 lvl=info msg="Config overridden from Environment variable" var="GF_PATHS_LOGS=/var/log/grafana"
2023-01-11 18:23:13 logger=settings t=2023-01-11T23:23:13.72+0000 lvl=info msg="Config overridden from Environment variable" var="GF_PATHS_PLUGINS=/var/lib/grafana-plugins"
2023-01-11 18:23:13 logger=settings t=2023-01-11T23:23:13.72+0000 lvl=info msg="Config overridden from Environment variable" var="GF_PATHS_PROVISIONING=/etc/grafana/provisioning"
2023-01-11 18:23:13 logger=settings t=2023-01-11T23:23:13.72+0000 lvl=info msg="Config overridden from Environment variable" var="GF_ANALYTICS_REPORTING_ENABLED=FALSE"
2023-01-11 18:23:13 logger=settings t=2023-01-11T23:23:13.72+0000 lvl=info msg="Config overridden from Environment variable" var="GF_SECURITY_ADMIN_USER=admin"
2023-01-11 18:23:13 logger=settings t=2023-01-11T23:23:13.72+0000 lvl=info msg="Config overridden from Environment variable" var="GF_SECURITY_ADMIN_PASSWORD=*********"
2023-01-11 18:23:13 logger=settings t=2023-01-11T23:23:13.72+0000 lvl=info msg="Config overridden from Environment variable" var="GF_SECURITY_DISABLE_GRAVATAR=true"
2023-01-11 18:23:13 logger=settings t=2023-01-11T23:23:13.72+0000 lvl=info msg="Config overridden from Environment variable" var="GF_SECURITY_ALLOW_EMBEDDING=true"
2023-01-11 18:23:13 logger=settings t=2023-01-11T23:23:13.72+0000 lvl=info msg="Config overridden from Environment variable" var="GF_USERS_ALLOW_SIGN_UP=false"
2023-01-11 18:23:13 logger=settings t=2023-01-11T23:23:13.72+0000 lvl=info msg="Config overridden from Environment variable" var="GF_AUTH_ANONYMOUS_ENABLED=false"
2023-01-11 18:23:13 logger=settings t=2023-01-11T23:23:13.72+0000 lvl=info msg="Config overridden from Environment variable" var="GF_AUTH_BASIC_ENABLED=false"
2023-01-11 18:23:13 logger=settings t=2023-01-11T23:23:13.72+0000 lvl=info msg="Config overridden from Environment variable" var="GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=natel-discrete-panel,pr0ps-trackmap-panel,panodata-map-panel,natel-plotly-panel"
2023-01-11 18:23:13 logger=settings t=2023-01-11T23:23:13.72+0000 lvl=info msg="Path Home" path=/usr/share/grafana
2023-01-11 18:23:13 logger=settings t=2023-01-11T23:23:13.72+0000 lvl=info msg="Path Data" path=/var/lib/grafana
2023-01-11 18:23:13 logger=settings t=2023-01-11T23:23:13.72+0000 lvl=info msg="Path Logs" path=/var/log/grafana
2023-01-11 18:23:13 logger=settings t=2023-01-11T23:23:13.72+0000 lvl=info msg="Path Plugins" path=/var/lib/grafana-plugins
2023-01-11 18:23:13 logger=settings t=2023-01-11T23:23:13.72+0000 lvl=info msg="Path Provisioning" path=/etc/grafana/provisioning
2023-01-11 18:23:13 logger=settings t=2023-01-11T23:23:13.72+0000 lvl=info msg="App mode production"
2023-01-11 18:23:13 logger=sqlstore t=2023-01-11T23:23:13.72+0000 lvl=info msg="Connecting to DB" dbtype=sqlite3


There's more if needed...
```

### Type of installation

Docker

### Version

Not sure

**Comment by prussell69** [comment]
An update to above...
I managed to get the plugin's installed, and setup the databases. The problem seems to start when I import a dashboard, any dashboard. Since the original dashboard I was importing had a lot of my own changes, I tried to import the original Powerwall-dashboard json file. Same crash!
Once it crashes, I don't know how to recover other than deleting the Grafana container, and the Grafana volume, then re-running the install script.
