### ISSUE TITLE
High CPU load since upgrade to 1.27.2

### ISSUE THREAD

**Issue by e-tplus** [teslamate-org/teslamate#3073]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I run Teslamate on a free tier of Google Cloud compute engine without problems for two years now. On Jan 15 I updated to 1.27.2 and since then the CPU load got from 20% to 80% which makes it slow to access. No drives were recorded since then but one charge.

### Expected Behavior

Should stay on 20%.

### Relevant log output

```shell
2023-01-17 12:30:25.918 [error] GenStateMachine :"1" terminating
teslamate_1  | ** (DBConnection.ConnectionError) tcp recv: closed (the connection was closed by the pool, possibly due to a timeout or because the pool has been terminated)
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:828: Ecto.Adapters.SQL.execute/6
teslamate_1  |     (ecto 3.9.4) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4
teslamate_1  |     (ecto 3.9.4) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
teslamate_1  |     (ecto 3.9.4) lib/ecto/repo/queryable.ex:151: Ecto.Repo.Queryable.one/3
teslamate_1  |     (teslamate 1.27.2) lib/teslamate/log.ex:292: TeslaMate.Log.close_drive/2
teslamate_1  |     (teslamate 1.27.2) lib/teslamate/vehicles/vehicle.ex:1024: anonymous fn/3 in TeslaMate.Vehicles.Vehicle.handle_event/4
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:1203: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
teslamate_1  | 2023-01-17 12:30:33.943 car_id=1 [info] Start / :online
teslamate_1  | 2023-01-17 12:30:38.829 car_id=1 [info] Connecting ...
teslamate_1  | 2023-01-17 12:31:24.747 [error] Postgrex.Protocol (#PID<0.2391.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.9714.1> timed out because it queued and checked out the connection for longer than 60000ms
teslamate_1  | 
teslamate_1  | #PID<0.9714.1> was at location:
teslamate_1  | 
teslamate_1  |     :prim_inet.recv0/3
teslamate_1  |     (postgrex 0.16.5) lib/postgrex/protocol.ex:3171: Postgrex.Protocol.msg_recv/4
teslamate_1  |     (postgrex 0.16.5) lib/postgrex/protocol.ex:2201: Postgrex.Protocol.recv_bind/3
teslamate_1  |     (postgrex 0.16.5) lib/postgrex/protocol.ex:2093: Postgrex.Protocol.bind_execute/4
teslamate_1  |     (db_connection 2.4.3) lib/db_connection/holder.ex:354: DBConnection.Holder.holder_apply/4
teslamate_1  |     (db_connection 2.4.3) lib/db_connection.ex:1413: DBConnection.run_execute/5
teslamate_1  |     (db_connection 2.4.3) lib/db_connection.ex:1508: DBConnection.run/6
teslamate_1  |     (db_connection 2.4.3) lib/db_connection.ex:644: DBConnection.parsed_prepare_execute/5
teslamate_1  | 
teslamate_1  | 2023-01-17 12:31:24.784 [error] GenStateMachine TeslaMate.Terrain terminating
teslamate_1  | ** (DBConnection.ConnectionError) tcp recv: closed (the connection was closed by the pool, possibly due to a timeout or because the pool has been terminated)
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:828: Ecto.Adapters.SQL.execute/6
teslamate_1  |     (ecto 3.9.4) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4
teslamate_1  |     (ecto 3.9.4) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
teslamate_1  |     (teslamate 1.27.2) lib/teslamate/log.ex:177: TeslaMate.Log.get_positions_without_elevation/2
teslamate_1  |     (teslamate 1.27.2) lib/teslamate/terrain.ex:84: TeslaMate.Terrain.handle_event/4
teslamate_1  |     (stdlib 3.17.2.1) gen_statem.erl:1205: :gen_statem.loop_state_callback/11
teslamate_1  |     (stdlib 3.17.2.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

### Screenshots

![cloud_Screenshot 2023-01-17 122719](https://user-images.githubusercontent.com/71662296/212890284-60f875b6-1c21-40bf-9c94-17bd8844d7dc.jpg)

### Type of installation

Docker

### Version

v1.27.2

**Comment by e-tplus** [comment]
CPU load has gone down to 7% now without any changes done. Drives are logged again. So closed.

**Comment by enoch85** [comment]
@e-tplus You know you can close your own issues right?
