### ISSUE TITLE
no with clause matching tortoise timeout error

### ISSUE THREAD

**Issue by brianmay** [teslamate-org/teslamate#3088]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Was browsing logs when I saw Elixir errors.

### Expected Behavior

No Elixir errors.

### Steps To Reproduce

No idea.

### Relevant log output

```shell
Oct 17 13:48:40 iot docker[51361]: 2022-10-17 02:48:40.832 [error] GenServer TeslaMate.Mqtt.Publisher terminating
Oct 17 13:48:40 iot docker[51361]: ** (WithClauseError) no with clause matching: {:error, :timeout}
Oct 17 13:48:40 iot docker[51361]:     (tortoise 0.10.0) lib/tortoise.ex:269: Tortoise.publish/4
Oct 17 13:48:40 iot docker[51361]:     (teslamate 1.27.1) lib/teslamate/mqtt/publisher.ex:41: TeslaMate.Mqtt.Publisher.handle_call/3
Oct 17 13:48:40 iot docker[51361]:     (stdlib 3.17.2) gen_server.erl:721: :gen_server.try_handle_call/4
Oct 17 13:48:40 iot docker[51361]:     (stdlib 3.17.2) gen_server.erl:750: :gen_server.handle_msg/6
Oct 17 13:48:40 iot docker[51361]:     (stdlib 3.17.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Oct 17 13:48:40 iot docker[51361]: Last message (from #PID<0.2531.0>): {:publish, "teslamate/cars/1/usable_battery_level", "72", [retain: true, qos: 1]}
Oct 17 13:48:40 iot docker[51361]: 2022-10-17 02:48:40.835 [error] Task #PID<0.2565.0> started from #PID<0.2524.0> terminating
Oct 17 13:48:40 iot docker[51361]: ** (stop) exited in: GenServer.call(TeslaMate.Mqtt.Publisher, {:publish, "teslamate/cars/1/charger_voltage", "0", [retain: true, qos: 1]}, 10000)
Oct 17 13:48:40 iot docker[51361]:     ** (EXIT) an exception was raised:
Oct 17 13:48:40 iot docker[51361]:         ** (WithClauseError) no with clause matching: {:error, :timeout}
Oct 17 13:48:40 iot docker[51361]:             (tortoise 0.10.0) lib/tortoise.ex:269: Tortoise.publish/4
Oct 17 13:48:40 iot docker[51361]:             (teslamate 1.27.1) lib/teslamate/mqtt/publisher.ex:41: TeslaMate.Mqtt.Publisher.handle_call/3
Oct 17 13:48:40 iot docker[51361]:             (stdlib 3.17.2) gen_server.erl:721: :gen_server.try_handle_call/4
Oct 17 13:48:40 iot docker[51361]:             (stdlib 3.17.2) gen_server.erl:750: :gen_server.handle_msg/6
Oct 17 13:48:40 iot docker[51361]:             (stdlib 3.17.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Oct 17 13:48:40 iot docker[51361]:     (elixir 1.13.4) lib/gen_server.ex:1030: GenServer.call/3
Oct 17 13:48:40 iot docker[51361]:     (elixir 1.13.4) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
Oct 17 13:48:40 iot docker[51361]:     (elixir 1.13.4) lib/task/supervised.ex:34: Task.Supervised.reply/4
Oct 17 13:48:40 iot docker[51361]:     (stdlib 3.17.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Oct 17 13:48:40 iot docker[51361]: Function: &:erlang.apply/2
Oct 17 13:48:40 iot docker[51361]:     Args: [#Function<4.122580145/1 in TeslaMate.Mqtt.PubSub.VehicleSubscriber.handle_info/2>, [charger_voltage: 0]]
Oct 17 13:48:40 iot docker[51361]: 2022-10-17 02:48:40.835 [error] Task #PID<0.2569.0> started from #PID<0.2524.0> terminating
Oct 17 13:48:40 iot docker[51361]: ** (stop) exited in: GenServer.call(TeslaMate.Mqtt.Publisher, {:publish, "teslamate/cars/1/ideal_battery_range_km", "303.65", [retain: true, qos: 1]}, 10000)
Oct 17 13:48:40 iot docker[51361]:     ** (EXIT) an exception was raised:
Oct 17 13:48:40 iot docker[51361]:         ** (WithClauseError) no with clause matching: {:error, :timeout}
Oct 17 13:48:40 iot docker[51361]:             (tortoise 0.10.0) lib/tortoise.ex:269: Tortoise.publish/4
Oct 17 13:48:40 iot docker[51361]:             (teslamate 1.27.1) lib/teslamate/mqtt/publisher.ex:41: TeslaMate.Mqtt.Publisher.handle_call/3
Oct 17 13:48:40 iot docker[51361]:             (stdlib 3.17.2) gen_server.erl:721: :gen_server.try_handle_call/4
Oct 17 13:48:40 iot docker[51361]:             (stdlib 3.17.2) gen_server.erl:750: :gen_server.handle_msg/6
Oct 17 13:48:40 iot docker[51361]:             (stdlib 3.17.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Oct 17 13:48:40 iot docker[51361]:     (elixir 1.13.4) lib/gen_server.ex:1030: GenServer.call/3
Oct 17 13:48:40 iot docker[51361]:     (elixir 1.13.4) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
Oct 17 13:48:40 iot docker[51361]:     (elixir 1.13.4) lib/task/supervised.ex:34: Task.Supervised.reply/4
Oct 17 13:48:40 iot docker[51361]:     (stdlib 3.17.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Oct 17 13:48:40 iot docker[51361]: Function: &:erlang.apply/2
Oct 17 13:48:40 iot docker[51361]:     Args: [#Function<4.122580145/1 in TeslaMate.Mqtt.PubSub.VehicleSubscriber.handle_info/2>, [ideal_battery_range_km: 303.65]]
Oct 17 13:48:40 iot docker[51361]: 2022-10-17 02:48:40.834 [error] Task #PID<0.2563.0> started from #PID<0.2524.0> terminating
Oct 17 13:48:40 iot docker[51361]: ** (stop) exited in: GenServer.call(TeslaMate.Mqtt.Publisher, {:publish, "teslamate/cars/1/doors_open", "false", [retain: true, qos: 1]}, 10000)
Oct 17 13:48:40 iot docker[51361]:     ** (EXIT) an exception was raised:
Oct 17 13:48:40 iot docker[51361]:         ** (WithClauseError) no with clause matching: {:error, :timeout}
Oct 17 13:48:40 iot docker[51361]:             (tortoise 0.10.0) lib/tortoise.ex:269: Tortoise.publish/4
Oct 17 13:48:40 iot docker[51361]:             (teslamate 1.27.1) lib/teslamate/mqtt/publisher.ex:41: TeslaMate.Mqtt.Publisher.handle_call/3
Oct 17 13:48:40 iot docker[51361]:             (stdlib 3.17.2) gen_server.erl:721: :gen_server.try_handle_call/4
Oct 17 13:48:40 iot docker[51361]:             (stdlib 3.17.2) gen_server.erl:750: :gen_server.handle_msg/6
Oct 17 13:48:40 iot docker[51361]:             (stdlib 3.17.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Oct 17 13:48:40 iot docker[51361]:     (elixir 1.13.4) lib/gen_server.ex:1030: GenServer.call/3
Oct 17 13:48:40 iot docker[51361]:     (elixir 1.13.4) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
Oct 17 13:48:40 iot docker[51361]:     (elixir 1.13.4) lib/task/supervised.ex:34: Task.Supervised.reply/4
Oct 17 13:48:40 iot docker[51361]:     (stdlib 3.17.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Oct 17 13:48:40 iot docker[51361]: Function: &:erlang.apply/2
Oct 17 13:48:40 iot docker[51361]:     Args: [#Function<4.122580145/1 in TeslaMate.Mqtt.PubSub.VehicleSubscriber.handle_info/2>, [doors_open: false]]
Oct 17 13:48:40 iot docker[51361]: 2022-10-17 02:48:40.835 [error] Task #PID<0.2566.0> started from #PID<0.2524.0> terminating
Oct 17 13:48:40 iot docker[51361]: ** (stop) exited in: GenServer.call(TeslaMate.Mqtt.Publisher, {:publish, "teslamate/cars/1/spoiler_type", "None", [retain: true, qos: 1]}, 10000)
Oct 17 13:48:40 iot docker[51361]:     ** (EXIT) an exception was raised:
Oct 17 13:48:40 iot docker[51361]:         ** (WithClauseError) no with clause matching: {:error, :timeout}
Oct 17 13:48:40 iot docker[51361]:             (tortoise 0.10.0) lib/tortoise.ex:269: Tortoise.publish/4
Oct 17 13:48:40 iot docker[51361]:             (teslamate 1.27.1) lib/teslamate/mqtt/publisher.ex:41: TeslaMate.Mqtt.Publisher.handle_call/3
Oct 17 13:48:40 iot docker[51361]:             (stdlib 3.17.2) gen_server.erl:721: :gen_server.try_handle_call/4
```

### Additional data

These aren't actually causing problems, so low priority, but shouldn't be happening, so I want to record them somewhere.

### Type of installation

Docker

### Version

1.27.2

**Comment by brianmay** [comment]
There should not be any timeout errors talking to my MQTT server. My suspicion this might be yet another Tortoise bug, which will be a world of pane because tortoise is no longer actively being maintained.

Possibly https://github.com/smartrent/tortoise311/ might be better, not convinced though this will be maintained any better.
