### ISSUE TITLE
Docker installation fails

### ISSUE THREAD

**Issue by toglader** [teslamate-org/teslamate#3166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I tried to install teslamate docker as guided in installation instructions but podtgresql fails to start.

See https://github.com/adriankumpf/teslamate/discussions/3159

### Relevant log output

```shell
Attaching to teslamate_teslamate_1
teslamate_1  | waiting for postgres at database:5432
teslamate_1  | 2023-03-27 18:06:32.427 [error] Postgrex.Protocol (#PID<0.166.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"
teslamate_1  | 2023-03-27 18:06:32.427 [error] Postgrex.Protocol (#PID<0.165.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"
teslamate_1  | 2023-03-27 18:06:33.980 [error] Postgrex.Protocol (#PID<0.166.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"
teslamate_1  | 2023-03-27 18:06:34.596 [error] Postgrex.Protocol (#PID<0.165.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"
teslamate_1  | 2023-03-27 18:06:35.346 [error] Could not create schema migrations table. This error usually happens due to the following:
teslamate_1  | 
teslamate_1  |   * The database does not exist
teslamate_1  |   * The "schema_migrations" table, which Ecto uses for managing
teslamate_1  |     migrations, was defined by another library
teslamate_1  |   * There is a deadlock while migrating (such as using concurrent
teslamate_1  |     indexes with a migration_lock)
teslamate_1  | 
teslamate_1  | To fix the first issue, run "mix ecto.create".
teslamate_1  | 
teslamate_1  | To address the second, you can run "mix ecto.drop" followed by
teslamate_1  | "mix ecto.create". Alternatively you may configure Ecto to use
teslamate_1  | another table and/or repository for managing migrations:
teslamate_1  | 
teslamate_1  |     config :teslamate, TeslaMate.Repo,
teslamate_1  |       migration_source: "some_other_table_for_schema_migrations",
teslamate_1  |       migration_repo: AnotherRepoForSchemaMigrations
teslamate_1  | 
teslamate_1  | The full error report is shown below.
teslamate_1  | 
teslamate_1  | ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2969ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
teslamate_1  | 
teslamate_1  |   1. Ensuring your database is available and that you can connect to it
teslamate_1  |   2. Tracking down slow queries and making sure they are running fast enough
teslamate_1  |   3. Increasing the pool_size (although this increases resource consumption)
teslamate_1  |   4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
teslamate_1  | 
teslamate_1  | See DBConnection.start_link/2 for more information
teslamate_1  | 
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate_1  |     (elixir 1.13.4) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:1005: Ecto.Adapters.SQL.execute_ddl/4
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/migrator.ex:677: Ecto.Migrator.verbose_schema_migration/3
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/migrator.ex:491: Ecto.Migrator.lock_for_migrations/4
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/migrator.ex:403: Ecto.Migrator.run/4
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/migrator.ex:146: Ecto.Migrator.with_repo/3
teslamate_1  |     (teslamate 1.27.2) lib/teslamate/release.ex:9: anonymous fn/2 in TeslaMate.Release.migrate/0
teslamate_1  | 2023-03-27 18:06:37.105 [error] Postgrex.Protocol (#PID<0.166.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"
teslamate_1  | 2023-03-27 18:06:37.105 [error] Postgrex.Protocol (#PID<0.165.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"
teslamate_1  | 2023-03-27 18:06:38.198 [error] Postgrex.Protocol (#PID<0.166.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"
teslamate_1  | 2023-03-27 18:06:39.767 [error] Postgrex.Protocol (#PID<0.165.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"
teslamate_1  | 2023-03-27 18:06:40.025 [error] Could not create schema migrations table. This error usually happens due to the following:
teslamate_1  | 
teslamate_1  |   * The database does not exist
teslamate_1  |   * The "schema_migrations" table, which Ecto uses for managing
teslamate_1  |     migrations, was defined by another library
teslamate_1  |   * There is a deadlock while migrating (such as using concurrent
teslamate_1  |     indexes with a migration_lock)
teslamate_1  | 
teslamate_1  | To fix the first issue, run "mix ecto.create".
teslamate_1  | 
teslamate_1  | To address the second, you can run "mix ecto.drop" followed by
teslamate_1  | "mix ecto.create". Alternatively you may configure Ecto to use
teslamate_1  | another table and/or repository for managing migrations:
teslamate_1  | 
teslamate_1  |     config :teslamate, TeslaMate.Repo,
teslamate_1  |       migration_source: "some_other_table_for_schema_migrations",
teslamate_1  |       migration_repo: AnotherRepoForSchemaMigrations
teslamate_1  | 
teslamate_1  | The full error report is shown below.
teslamate_1  | 
teslamate_1  | ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2972ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
teslamate_1  | 
teslamate_1  |   1. Ensuring your database is available and that you can connect to it
teslamate_1  |   2. Tracking down slow queries and making sure they are running fast enough
teslamate_1  |   3. Increasing the pool_size (although this increases resource consumption)
teslamate_1  |   4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
teslamate_1  | 
teslamate_1  | See DBConnection.start_link/2 for more information
teslamate_1  | 
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate_1  |     (elixir 1.13.4) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:1005: Ecto.Adapters.SQL.execute_ddl/4
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/migrator.ex:677: Ecto.Migrator.verbose_schema_migration/3
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/migrator.ex:491: Ecto.Migrator.lock_for_migrations/4
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/migrator.ex:403: Ecto.Migrator.run/4
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/migrator.ex:146: Ecto.Migrator.with_repo/3
teslamate_1  |     (teslamate 1.27.2) lib/teslamate/release.ex:9: anonymous fn/2 in TeslaMate.Release.migrate/0
teslamate_1  | 2023-03-27 18:06:47.155 [error] Postgrex.Protocol (#PID<0.166.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"
teslamate_1  | 2023-03-27 18:06:47.155 [error] Postgrex.Protocol (#PID<0.165.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"
teslamate_1  | 2023-03-27 18:06:49.317 [error] Postgrex.Protocol (#PID<0.166.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"
teslamate_1  | 2023-03-27 18:06:49.977 [error] Postgrex.Protocol (#PID<0.165.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"
teslamate_1  | 2023-03-27 18:06:50.081 [error] Could not create schema migrations table. This error usually happens due to the following:
teslamate_1  | 
teslamate_1  |   * The database does not exist
teslamate_1  |   * The "schema_migrations" table, which Ecto uses for managing
teslamate_1  |     migrations, was defined by another library
teslamate_1  |   * There is a deadlock while migrating (such as using concurrent
teslamate_1  |     indexes with a migration_lock)
teslamate_1  | 
teslamate_1  | To fix the first issue, run "mix ecto.create".
teslamate_1  | 
teslamate_1  | To address the second, you can run "mix ecto.drop" followed by
teslamate_1  | "mix ecto.create". Alternatively you may configure Ecto to use
teslamate_1  | another table and/or repository for managing migrations:
teslamate_1  | 
teslamate_1  |     config :teslamate, TeslaMate.Repo,
teslamate_1  |       migration_source: "some_other_table_for_schema_migrations",
teslamate_1  |       migration_repo: AnotherRepoForSchemaMigrations
teslamate_1  | 
teslamate_1  | The full error report is shown below.
teslamate_1  | 
teslamate_1  | ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2975ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
teslamate_1  | 
teslamate_1  |   1. Ensuring your database is available and that you can connect to it
teslamate_1  |   2. Tracking down slow queries and making sure they are running fast enough
teslamate_1  |   3. Increasing the pool_size (although this increases resource consumption)
teslamate_1  |   4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
teslamate_1  | 
teslamate_1  | See DBConnection.start_link/2 for more information
teslamate_1  | 
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate_1  |     (elixir 1.13.4) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:1005: Ecto.Adapters.SQL.execute_ddl/4
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/migrator.ex:677: Ecto.Migrator.verbose_schema_migration/3
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/migrator.ex:491: Ecto.Migrator.lock_for_migrations/4
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/migrator.ex:403: Ecto.Migrator.run/4
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/migrator.ex:146: Ecto.Migrator.with_repo/3
teslamate_1  |     (teslamate 1.27.2) lib/teslamate/release.ex:9: anonymous fn/2 in TeslaMate.Release.migrate/0
teslamate_1  | 2023-03-27 18:06:52.128 [error] Postgrex.Protocol (#PID<0.166.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"
teslamate_1  | 2023-03-27 18:06:52.128 [error] Postgrex.Protocol (#PID<0.165.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"
teslamate_1  | 2023-03-27 18:06:54.286 [error] Postgrex.Protocol (#PID<0.165.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"
teslamate_1  | 2023-03-27 18:06:54.592 [error] Postgrex.Protocol (#PID<0.166.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"
teslamate_1  | 2023-03-27 18:06:55.051 [error] Could not create schema migrations table. This error usually happens due to the following:
teslamate_1  | 
teslamate_1  |   * The database does not exist
teslamate_1  |   * The "schema_migrations" table, which Ecto uses for managing
teslamate_1  |     migrations, was defined by another library
teslamate_1  |   * There is a deadlock while migrating (such as using concurrent
teslamate_1  |     indexes with a migration_lock)
teslamate_1  | 
teslamate_1  | To fix the first issue, run "mix ecto.create".
teslamate_1  | 
teslamate_1  | To address the second, you can run "mix ecto.drop" followed by
teslamate_1  | "mix ecto.create". Alternatively you may configure Ecto to use
teslamate_1  | another table and/or repository for managing migrations:
teslamate_1  | 
teslamate_1  |     config :teslamate, TeslaMate.Repo,
teslamate_1  |       migration_source: "some_other_table_for_schema_migrations",
teslamate_1  |       migration_repo: AnotherRepoForSchemaMigrations
teslamate_1  | 
teslamate_1  | The full error report is shown below.
teslamate_1  | 
teslamate_1  | ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2973ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
teslamate_1  | 
teslamate_1  |   1. Ensuring your database is available and that you can connect to it
teslamate_1  |   2. Tracking down slow queries and making sure they are running fast enough
teslamate_1  |   3. Increasing the pool_size (although this increases resource consumption)
teslamate_1  |   4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
teslamate_1  | 
teslamate_1  | See DBConnection.start_link/2 for more information
teslamate_1  | 
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate_1  |     (elixir 1.13.4) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:1005: Ecto.Adapters.SQL.execute_ddl/4
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/migrator.ex:677: Ecto.Migrator.verbose_schema_migration/3
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/migrator.ex:491: Ecto.Migrator.lock_for_migrations/4
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/migrator.ex:403: Ecto.Migrator.run/4
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/migrator.ex:146: Ecto.Migrator.with_repo/3
teslamate_1  |     (teslamate 1.27.2) lib/teslamate/release.ex:9: anonymous fn/2 in TeslaMate.Release.migrate/0
teslamate_1  | 2023-03-27 18:06:57.452 [error] Postgrex.Protocol (#PID<0.166.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"
teslamate_1  | 2023-03-27 18:06:57.452 [error] Postgrex.Protocol (#PID<0.165.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"
teslamate_1  | 2023-03-27 18:07:00.021 [error] Postgrex.Protocol (#PID<0.165.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"
teslamate_1  | 2023-03-27 18:07:00.032 [error] Postgrex.Protocol (#PID<0.166.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"
teslamate_1  | 2023-03-27 18:07:00.375 [error] Could not create schema migrations table. This error usually happens due to the following:
teslamate_1  | 
teslamate_1  |   * The database does not exist
teslamate_1  |   * The "schema_migrations" table, which Ecto uses for managing
teslamate_1  |     migrations, was defined by another library
teslamate_1  |   * There is a deadlock while migrating (such as using concurrent
teslamate_1  |     indexes with a migration_lock)
teslamate_1  | 
teslamate_1  | To fix the first issue, run "mix ecto.create".
teslamate_1  | 
teslamate_1  | To address the second, you can run "mix ecto.drop" followed by
teslamate_1  | "mix ecto.create". Alternatively you may configure Ecto to use
teslamate_1  | another table and/or repository for managing migrations:
teslamate_1  | 
teslamate_1  |     config :teslamate, TeslaMate.Repo,
teslamate_1  |       migration_source: "some_other_table_for_schema_migrations",
teslamate_1  |       migration_repo: AnotherRepoForSchemaMigrations
teslamate_1  | 
teslamate_1  | The full error report is shown below.
teslamate_1  | 
teslamate_1  | ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2976ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
teslamate_1  | 
teslamate_1  |   1. Ensuring your database is available and that you can connect to it
teslamate_1  |   2. Tracking down slow queries and making sure they are running fast enough
teslamate_1  |   3. Increasing the pool_size (although this increases resource consumption)
teslamate_1  |   4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
teslamate_1  | 
teslamate_1  | See DBConnection.start_link/2 for more information
teslamate_1  | 
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate_1  |     (elixir 1.13.4) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:1005: Ecto.Adapters.SQL.execute_ddl/4
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/migrator.ex:677: Ecto.Migrator.verbose_schema_migration/3
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/migrator.ex:491: Ecto.Migrator.lock_for_migrations/4
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/migrator.ex:403: Ecto.Migrator.run/4
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/migrator.ex:146: Ecto.Migrator.with_repo/3
teslamate_1  |     (teslamate 1.27.2) lib/teslamate/release.ex:9: anonymous fn/2 in TeslaMate.Release.migrate/0
teslamate_1  | 2023-03-27 18:07:03.573 [error] Postgrex.Protocol (#PID<0.166.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"
teslamate_1  | 2023-03-27 18:07:03.573 [error] Postgrex.Protocol (#PID<0.165.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"
teslamate_1  | 2023-03-27 18:07:04.975 [error] Postgrex.Protocol (#PID<0.166.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"
teslamate_1  | 2023-03-27 18:07:05.715 [error] Postgrex.Protocol (#PID<0.165.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"
teslamate_1  | 2023-03-27 18:07:06.495 [error] Could not create schema migrations table. This error usually happens due to the following:
teslamate_1  | 
teslamate_1  |   * The database does not exist
teslamate_1  |   * The "schema_migrations" table, which Ecto uses for managing
teslamate_1  |     migrations, was defined by another library
teslamate_1  |   * There is a deadlock while migrating (such as using concurrent
teslamate_1  |     indexes with a migration_lock)
teslamate_1  | 
teslamate_1  | To fix the first issue, run "mix ecto.create".
teslamate_1  | 
teslamate_1  | To address the second, you can run "mix ecto.drop" followed by
teslamate_1  | "mix ecto.create". Alternatively you may configure Ecto to use
teslamate_1  | another table and/or repository for managing migrations:
teslamate_1  | 
teslamate_1  |     config :teslamate, TeslaMate.Repo,
teslamate_1  |       migration_source: "some_other_table_for_schema_migrations",
teslamate_1  |       migration_repo: AnotherRepoForSchemaMigrations
teslamate_1  | 
teslamate_1  | The full error report is shown below.
teslamate_1  | 
teslamate_1  | ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2972ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
teslamate_1  | 
teslamate_1  |   1. Ensuring your database is available and that you can connect to it
teslamate_1  |   2. Tracking down slow queries and making sure they are running fast enough
teslamate_1  |   3. Increasing the pool_size (although this increases resource consumption)
teslamate_1  |   4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
teslamate_1  | 
teslamate_1  | See DBConnection.start_link/2 for more information
teslamate_1  | 
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate_1  |     (elixir 1.13.4) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:1005: Ecto.Adapters.SQL.execute_ddl/4
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/migrator.ex:677: Ecto.Migrator.verbose_schema_migration/3
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/migrator.ex:491: Ecto.Migrator.lock_for_migrations/4
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/migrator.ex:403: Ecto.Migrator.run/4
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/migrator.ex:146: Ecto.Migrator.with_repo/3
teslamate_1  |     (teslamate 1.27.2) lib/teslamate/release.ex:9: anonymous fn/2 in TeslaMate.Release.migrate/0
teslamate_1  | 2023-03-27 18:07:11.268 [error] Postgrex.Protocol (#PID<0.166.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"
teslamate_1  | 2023-03-27 18:07:11.268 [error] Postgrex.Protocol (#PID<0.165.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"
teslamate_1  | 2023-03-27 18:07:12.803 [error] Postgrex.Protocol (#PID<0.165.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"
teslamate_1  | 2023-03-27 18:07:13.265 [error] Postgrex.Protocol (#PID<0.166.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"
teslamate_1  | 2023-03-27 18:07:14.199 [error] Could not create schema migrations table. This error usually happens due to the following:
teslamate_1  | 
teslamate_1  |   * The database does not exist
teslamate_1  |   * The "schema_migrations" table, which Ecto uses for managing
teslamate_1  |     migrations, was defined by another library
teslamate_1  |   * There is a deadlock while migrating (such as using concurrent
teslamate_1  |     indexes with a migration_lock)
teslamate_1  | 
teslamate_1  | To fix the first issue, run "mix ecto.create".
teslamate_1  | 
teslamate_1  | To address the second, you can run "mix ecto.drop" followed by
teslamate_1  | "mix ecto.create". Alternatively you may configure Ecto to use
teslamate_1  | another table and/or repository for managing migrations:
teslamate_1  | 
teslamate_1  |     config :teslamate, TeslaMate.Repo,
teslamate_1  |       migration_source: "some_other_table_for_schema_migrations",
teslamate_1  |       migration_repo: AnotherRepoForSchemaMigrations
teslamate_1  | 
teslamate_1  | The full error report is shown below.
teslamate_1  | 
teslamate_1  | ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2976ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
teslamate_1  | 
teslamate_1  |   1. Ensuring your database is available and that you can connect to it
teslamate_1  |   2. Tracking down slow queries and making sure they are running fast enough
teslamate_1  |   3. Increasing the pool_size (although this increases resource consumption)
teslamate_1  |   4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
teslamate_1  | 
teslamate_1  | See DBConnection.start_link/2 for more information
teslamate_1  | 
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate_1  |     (elixir 1.13.4) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:1005: Ecto.Adapters.SQL.execute_ddl/4
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/migrator.ex:677: Ecto.Migrator.verbose_schema_migration/3
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/migrator.ex:491: Ecto.Migrator.lock_for_migrations/4
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/migrator.ex:403: Ecto.Migrator.run/4
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/migrator.ex:146: Ecto.Migrator.with_repo/3
teslamate_1  |     (teslamate 1.27.2) lib/teslamate/release.ex:9: anonymous fn/2 in TeslaMate.Release.migrate/0
```

### Type of installation

Docker

### Version

latest

**Comment by guldil** [comment]
Same here when i first try docker version of teslamate. 

I though it came from my "old" ubuntu version so i go to "manual installation" which works perfectly. 

Look like database schema is not created in docker.

**Comment by Thom1984** [comment]
i have the same issue. Is there a solution?

**Comment by brianmay** [comment]
The errors seem to be saying you already have a schema_migrations table. Did you start with a clean database?

**Comment by brianmay** [comment]
This looks similar to #3122, make sure the database is up and running. It actually looks like it cannot connect to your database for some reason.

```
teslamate_1  | 2023-03-27 18:07:03.573 [error] Postgrex.Protocol (#PID<0.166.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"
teslamate_1  | 2023-03-27 18:07:03.573 [error] Postgrex.Protocol (#PID<0.165.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"
teslamate_1  | 2023-03-27 18:07:04.975 [error] Postgrex.Protocol (#PID<0.166.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"
teslamate_1  | 2023-03-27 18:07:05.715 [error] Postgrex.Protocol (#PID<0.165.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "teslamate"
```

**Comment by Stoobiedoo** [comment]
I have the same problem. I started for the first time with TeslaMate this weekend with the Docker recommended settings. The Grafana instance can see the database no problem via the "Save & Test" results.  This is on Ubuntu 22.04.2 LTS

Any other tips for testing the database connection?

**Comment by Thom1984** [comment]
I had a problem with the password, in my docker-compose.yml was a space present before the password. Now it works fine

**Comment by Stoobiedoo** [comment]
> I had a problem with the password, in my docker-compose.yml was a space present before the password. Now it works fine

Thanks! I checked again and thought I had removed them all, but found one more.

**Comment by 1990marco1990** [comment]
Same problem nothing works with the docker.

**Comment by JakobLichterfeld** [comment]
Make sure to  use correct credentials in your docker-compose.yml: 

`password authentication failed for user "teslamate"`

**Comment by netzpixel** [comment]
Any updates? I have the same problem and the manual setup sucks...

**Comment by JakobLichterfeld** [comment]
As wrote above, issue of OP is related to bad password and solved by setting correct.

**Comment by toglader** [comment]
How should I change the password and where? Even reinstallation of everything doesn't help

**Comment by DrMichael** [comment]
You are setting the password in `docker-compose.yml`.

**Comment by netzpixel** [comment]
> How should I change the password and where? Even reinstallation of everything doesn't help

Like I wrote, redoing it all isn’t enough. You also have to delete the related volumes because the wrong data is saved there and not being overwritten.
