### ISSUE TITLE
Settings - Internal Server Error

### ISSUE THREAD

**Issue by Dulanic** [teslamate-org/teslamate#3414]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After recent update, settings page no longer is working.

### Expected Behavior

Settings page works.

### Steps To Reproduce

Unknown

### Relevant log output

```shell
2023-11-12 15:59:43.288 [info] GET /settings
2023-11-12 15:59:43.292 [info] Sent 500 in 4ms
2023-11-12 15:59:43.292 [error] #PID<0.2662.0> running TeslaMateWeb.Endpoint (connection #PID<0.2646.0>, stream id 7) terminated
Server: 192.168.2.155:4000 (http)
Request: GET /settings
** (exit) an exception was raised:
    ** (KeyError) key :id not found in: nil

If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map
        (teslamate 1.27.4) lib/teslamate_web/live/settings_live/index.ex:183: anonymous fn/2 in TeslaMateWeb.SettingsLive.Index.prepare/1
        (elixir 1.15.7) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
        (teslamate 1.27.4) lib/teslamate_web/live/settings_live/index.ex:15: TeslaMateWeb.SettingsLive.Index.mount/3
        (phoenix_live_view 0.17.14) lib/phoenix_live_view/utils.ex:301: anonymous fn/6 in Phoenix.LiveView.Utils.maybe_call_live_view_mount!/5
        (telemetry 1.2.1) /opt/app/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
        (phoenix_live_view 0.17.14) lib/phoenix_live_view/static.ex:270: Phoenix.LiveView.Static.call_mount_and_handle_params!/5
        (phoenix_live_view 0.17.14) lib/phoenix_live_view/static.ex:110: Phoenix.LiveView.Static.render/3
        (phoenix_live_view 0.17.14) lib/phoenix_live_view/controller.ex:39: Phoenix.LiveView.Controller.live_render/3
```

### Additional data

N/A

### Type of installation

Docker

### Version

1.27.4

**Comment by JakobLichterfeld** [comment]
Can't reproduce, test passed, behavior is as expected.

**Comment by Dulanic** [comment]
It's happening even if I use ip, it's deft not network related. It's very weird. The log is from the container so it's def Tesla mate.

**Comment by Dulanic** [comment]
It is not a network issue.... the other pages work fine. It worked fine before the update, now it does. Thart error was from teslamate, which means it received the request. Only settings doesn't work and shows Internal Server Error.

![image](https://github.com/teslamate-org/teslamate/assets/2948206/94709770-bf50-4d3b-be55-8b888a464ca6)
![image](https://github.com/teslamate-org/teslamate/assets/2948206/360ee1ff-688e-4a51-a2d8-7ae7c2d0599e)

**Comment by JakobLichterfeld** [comment]
So it's a network issue, you do not spin up any Postgres server. Please use full docker-compose setup as explained in docu https://docs.teslamate.org/docs/installation/docker/

**Comment by Dulanic** [comment]
No it's not lol. I have postgres on proxmox, how else would the other pages
work fine.

**Comment by Dulanic** [comment]
No it's not lol. I have postgres on proxmox, how else would the other pages work fine. I don't mean to sound like a jerk, but this is kind of obvious that it shows the charging info in the screenshot I posted. I've had this setup for a long time and it works fine. So yes all in docker works, but its NOT a requirement. As long as you have a postgres server its fine.

![image](https://github.com/teslamate-org/teslamate/assets/2948206/0b8db240-ba2a-4c06-8740-449c07c3ccd9)

**Comment by JakobLichterfeld** [comment]
TeslaMate webpage shows live values, not values stored in db, innit?
I assumed you spun up a postgres, but you didn't share it. As you spin it up using proxmox and the logs given, it still seems to be a networking issue within your proxmox.

**Comment by Dulanic** [comment]
> TeslaMate webpage shows live values, not values stored in db, innit? I assumed you spun up a postgres, but you didn't share it. As you spin it up using proxmox and the logs given, it still seems to be a networking issue within your proxmox.

True, but if you dont have a DB its connected to, it doesnt have the API keys as those are stored in tokens postgres table. Same for the geofences.

**Comment by Dulanic** [comment]
I almost wonder if it's a.... table problem? Or a query problem to the table.

**Comment by Dulanic** [comment]
Also this person had same problem, so it isnt only me. https://github.com/teslamate-org/teslamate/issues/3258

**Comment by parkr** [comment]
Your car should have a row and an ID in the database I think. Most are ID `1`. 

It seems like it's accessing `car.id` but `car` is nil (https://github.com/teslamate-org/teslamate/blob/master/lib/teslamate_web/live/settings_live/index.ex#L183).

**Comment by Dulanic** [comment]
I wonder if it's because my car is 3 but my settings is 1.... I tried changing my settings to #3 but that did nothing.

**Comment by Dulanic** [comment]
I DID find a settings_id in the car table, which I changed to 1. But that did not resolve.

**Comment by JakobLichterfeld** [comment]
> Maybe it shows live, not sure, but if you dont have a DB its connected to, it doesnt have the API keys as those are stored in tokens postgres table. Same for the geofences.

You are right, my fault. So your logs show that the db query returned nil for the GET /settings so it looks like your db is missing the settings table completely. 
Since you did not share your postgres setup in detail, I assume you are on an old or unsupported version or have upgraded the postgres version without following the steps in the doc to do so. The db cleanup and restore from backup will trigger a db schema migration. See https://docs.teslamate.org/docs/maintenance/upgrading_postgres

**Comment by cleanev** [comment]
> Also this person had same problem, so it isnt only me. #3258

I did report during initial fixes by various developers and later added a discussion topic but went unanswered [https://github.com/teslamate-org/teslamate/discussions/3412#discussion-5844438](url)

**Comment by JakobLichterfeld** [comment]
All test cases for the settings page still pass, no change here either.
So I still assume there is an issue on your end. Have you tried without the browser cache? There is the rare chance that it is related to the language settings imo.

**Comment by cleanev** [comment]
Thanks @JakobLichterfeld -
I conducted tests this morning, all devices are EST based in US
- MS Edge on Windows 11 - with and without private mode
- Mac Sonoma - with and without private mode
- iPadOS - with and without private mode

All six end up with ‘Internal server error’, docker errors remain the same all along, latest error from iPadOS in private mode is attached 
2023-11-17 13:21:18.551 [error] #PID<0.91873.0> running TeslaMateWeb.Endpoint (connection #PID<0.91854.0>, stream id 6) terminated
Server: 10.2.2.7:4000 (http)
Request: GET /settings
** (exit) an exception was raised:
    ** (KeyError) key :id not found in: nil
If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map
        (teslamate 1.27.4) lib/teslamate_web/live/settings_live/index.ex:183: anonymous fn/2 in TeslaMateWeb.SettingsLive.Index.prepare/1
        (elixir 1.15.7) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
        (teslamate 1.27.4) lib/teslamate_web/live/settings_live/index.ex:15: TeslaMateWeb.SettingsLive.Index.mount/3
        (phoenix_live_view 0.17.14) lib/phoenix_live_view/utils.ex:301: anonymous fn/6 in Phoenix.LiveView.Utils.maybe_call_live_view_mount!/5
        (telemetry 1.2.1) /opt/app/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
        (phoenix_live_view 0.17.14) lib/phoenix_live_view/static.ex:270: Phoenix.LiveView.Static.call_mount_and_handle_params!/5
        (phoenix_live_view 0.17.14) lib/phoenix_live_view/static.ex:110: Phoenix.LiveView.Static.render/3
        (phoenix_live_view 0.17.14) lib/phoenix_live_view/controller.ex:39: Phoenix.LiveView.Controller.live_render/3

**Comment by JakobLichterfeld** [comment]
At least we tried, so let's investigate further.

**Comment by cleanev** [comment]
Neither 1.28.1 or 1.28.2 fixed this issue. I did not see any mention about this issue in release notes but thought of upgrading to see if there may have been anything related to this issue

Not sure if anyone else with this issue on this thread tried and seen any change.

@Dulanic  - is there any way to find all rows in various tables in database related to car-id that may still linger from past rental though when I run the select command mine lists only a single car with car-id of 1.

**Comment by Dulanic** [comment]
I have the same issue, we haven't found a fix thus far.

**Comment by cwanja** [comment]
> @Dulanic  - is there any way to find all rows in various tables in database related to car-id that may still linger from past rental though when I run the select command mine lists only a single car with car-id of 1.

You can check the following tables, they all reference a `car_id`. Ignore the 'DELETE FROM'. 

DELETE FROM cars WHERE id = num;
DELETE FROM car_settings WHERE id = num;
DELETE FROM charging_processes WHERE car_id = num;
DELETE from charges WHERE charging_process_id in (select id from charging_processes where car_id = num);
DELETE FROM drives WHERE car_id = num;
DELETE FROM positions WHERE car_id = num;
DELETE FROM states WHERE car_id = num;
DELETE FROM updates WHERE car_id = num;

It definitely seems focused around your settings table. Can one of you output your settings table, removing any identifiable information? Probably mainly VIN.

**Comment by Dulanic** [comment]
Think I provided it before, But here it is again.
![image](https://github.com/teslamate-org/teslamate/assets/2948206/2466c830-de2c-45de-9f8b-dc61fca8e28c)
![image](https://github.com/teslamate-org/teslamate/assets/2948206/8c7a9b94-300d-45c6-af38-8dbc577117ba)

**Comment by JakobLichterfeld** [comment]
Seems like you do not have a car id 1 which causes the error

**Comment by cwanja** [comment]
> Think I provided it before, But here it is again. ![image](https://private-user-images.githubusercontent.com/2948206/287265144-2466c830-de2c-45de-9f8b-dc61fca8e28c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0NDIyMTUsIm5iZiI6MTcwMTQ0MTkxNSwicGF0aCI6Ii8yOTQ4MjA2LzI4NzI2NTE0NC0yNDY2YzgzMC1kZTJjLTQ1ZGUtOWY4Yi1kYzYxZmNhOGUyOGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDFUMTQ0NTE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDJjMGI0MzFmNzBkYzc0OWM4ZmM1NzdjZDMxYTA5NGNjNTM3MTkyNmMyMWVhYzBkZTc1ZDllOWViOWZlOTYyMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.XMXsN1GnGoiJiBzI9eBrqsgbLbaKMGPq_sE6X3ZJ7Qk) ![image](https://private-user-images.githubusercontent.com/2948206/287265485-8c7a9b94-300d-45c6-af38-8dbc577117ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0NDIyMTUsIm5iZiI6MTcwMTQ0MTkxNSwicGF0aCI6Ii8yOTQ4MjA2LzI4NzI2NTQ4NS04YzdhOWI5NC0zMDBkLTQ1YzYtYWYzOC04ZGJjNTc3MTE3YmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDFUMTQ0NTE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGQxZGZkOWE5ZWUwNDBhNDE0MzAxM2FmYzMwYjcyY2Y2ZjBhNmM1ZWIxYmI5ZTcyNzEyMTk1ZTNkNmZmMDQ2ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IziRtAUh9nMw7aRvcRTB2pjUGjPD9FexFsWkW818y2g)

What is in your `car_settings` table? Leaning similar to @JakobLichterfeld that it is trying to display other car details since your `cars` tables first ID is 3.

**Comment by Dulanic** [comment]
> Seems like you do not have a car id 1 which causes the error

No, check settings, it said the car_id is 3. It makes sense, it is my 3rd tesla.

**Comment by Dulanic** [comment]
@cwanja I did, but I got rid of those vehicles so I purged their data,

![image](https://github.com/teslamate-org/teslamate/assets/2948206/464c2294-27ef-4531-a199-d623ed3fdd0f)

**Comment by Dulanic** [comment]
Fixed! I deleted id 3 in car_settings. I thought it would be 1, which I found deleted my whole data so I had to restore from a backup, but once I restored, I deleted 3 and boom fixed!

Others who have this problem... #1 make sure you have a backup because you make break things like I did during my testing..., but #2 delete the id from car_settings that DOESNT match your settings id in public.settings.

**Comment by cwanja** [comment]
Woot woot! 🎉

**Comment by cleanev** [comment]
Sorry to reopen this guys, but I am another one who has been affected. 
When I run below command I get only single car. I’m not a database guru but can follow guidance to get necessary output to resolve my issue. 

I had a loaner a while back (almost a year now) and I removed it following some guidance on this forum and things were OK till now. thanks for your help in advance.

teslamate=# SELECT id, vin FROM cars;
 id |        vin        
----+-------------------
  1 | 5YJ3E1EA3XXXXXXXX
(1 row)
Removed last 8 alpha numeric.

@cwanja - from the commands you highlighted I tried to run like so by removing delete from, but there is no output and none comes up with any results. I’m missing something for sure

teslamate=# select cars where id_num = 1
teslamate-#

**Comment by cwanja** [comment]
> Sorry to reopen this guys, but I am another one who has been affected. When I run below command I get only single car. I’m not a database guru but can follow guidance to get necessary output to resolve my issue.
> 
> I had a loaner a while back (almost a year now) and I removed it following some guidance on this forum and things were OK till now. thanks for your help in advance.
> 
> teslamate=# SELECT id, vin FROM cars; id | vin ----+------------------- 1 | 5YJ3E1EA3XXXXXXXX (1 row) Removed last 8 alpha numeric.
> 
> @cwanja - from the commands you highlighted I tried to run like so by removing delete from, but there is no output and none comes up with any results. I’m missing something for sure
> 
> teslamate=# select cars where id_num = 1 teslamate-#

No need to apologize. Sorry about that previous paragraph of commands, it was confusing the way I worded it. Was more intended to list where a linger `car_id` could be in tables. 

What do you get when you run:
- `select * from cars;`
- `select * from car_settings;`
- `select * from settings;`

I have a feeling you have a lingering ID from that loaner around and it is breaking the settings page.

**Comment by cwanja** [comment]
> Is there any additional step remaining? Before I close out the ssh session?

Nope you are good. 

> BTW if I run 3 commands you mentioned above
> Select statements 2 & 3 does not have any output
> Where as select 1 shows my current car

That should not be intended. Feel free to open Discussion if you want to dive further.

**Comment by loyalsnoopdoge** [comment]
I'm experiencing this issue and none of the above fixes have worked for me. Please let me know what logs you need
