### ISSUE TITLE
Cannot get current car status

### ISSUE THREAD

**Issue by jblum66** [teslamate-org/teslamate#3457]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When my car is asleep, the Teslamate plugin displays old car status (from 7 days). When my car is awaken, Teslamate says car status is unavailable. No data recording in the timeline since 2023-11-10.

To try to solve this problem, I updated the Teslamate Docker containers. Then I logged out from Teslamate, generated new Tesla tokens and logged in again.

In the logs I find errors:

### Relevant log output

```shell
teslamate_1  | 2023-11-19 15:44:55.924 [info] Starting logger for 'JBL'
teslamate_1  | 2023-11-19 15:44:56.290 car_id=1 [info] Start / :online
teslamate_1  | 2023-11-19 15:44:56.296 [error] GenStateMachine :"1" terminating
teslamate_1  | ** (MatchError) no match of right hand side value: {:error, #Ecto.Changeset<action: :insert, changes: %{date: ~U[2023-11-19 15:44:55.983000Z], power: 0, odometer: 59814.48684, battery_heater: false, driver_temp_setting: Decimal.new("19.0"), fan_status: 0, inside_temp: Decimal.new("16.6"), is_climate_on: false, is_front_defroster_on: false, is_rear_defroster_on: false, outside_temp: Decimal.new("13.0"), passenger_temp_setting: Decimal.new("19.0"), battery_heater_on: false, battery_level: 66, usable_battery_level: 65, tpms_pressure_fl: Decimal.new("2.75"), tpms_pressure_fr: Decimal.new("2.8"), tpms_pressure_rl: Decimal.new("2.8"), tpms_pressure_rr: Decimal.new("2.85"), ideal_battery_range_km: Decimal.new("260.67"), rated_battery_range_km: Decimal.new("260.67"), est_battery_range_km: Decimal.new("213.06")}, errors: [latitude: {"can't be blank", [validation: :required]}, longitude: {"can't be blank", [validation: :required]}], data: #TeslaMate.Log.Position<>, valid?: false>}
teslamate_1  |     (teslamate 1.27.3) lib/teslamate/vehicles/vehicle.ex:721: anonymous fn/4 in TeslaMate.Vehicles.Vehicle.handle_event/4
teslamate_1  |     (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:1203: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
teslamate_1  |     (db_connection 2.5.0) lib/db_connection.ex:1630: DBConnection.run_transaction/4
teslamate_1  |     (teslamate 1.27.3) lib/teslamate/vehicles/vehicle.ex:713: TeslaMate.Vehicles.Vehicle.handle_event/4
teslamate_1  |     (stdlib 5.0.1) gen_statem.erl:1379: :gen_statem.loop_state_callback/11
teslamate_1  |     (stdlib 5.0.1) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
teslamate_1  | 2023-11-19 15:44:56.336 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/1493010042294218 -> 429 (37.073 ms)
teslamate_1  | 2023-11-19 15:44:56.336 [warning] TeslaApi.Error / "Retry later\n"
teslamate_1  | 2023-11-19 15:44:56.336 car_id=1 [error] Error / :unknown
```

### Screenshots

![image](https://github.com/teslamate-org/teslamate/assets/9610962/84948a78-6387-41b3-b4e5-f664393358c5)

![image](https://github.com/teslamate-org/teslamate/assets/9610962/4260cb60-25c7-4c9c-ae77-fcedf9a9d628)

### Type of installation

Docker

### Version

v1.27.3

**Comment by cwanja** [comment]
Update TeslaMate to 1.27.4.

**Comment by jblum66** [comment]
That works! Thank you and sorry: I forgot to update my docker-compose.yml file.

**Comment by cwanja** [comment]
No need to apologize! Glad it's working.
