### ISSUE TITLE
MQTT Timeout / WithClauseError / Tortoise issue?

### ISSUE THREAD

**Issue by BSkando** [teslamate-org/teslamate#3519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

No matter what, I cannot get teslamate to work with my MQTT broker.  It is definitely not an issue on the MQTT side, as I have several applications publishing with no problems.

I've tried authenticated as well as turned off authentication and tried anonymous.  Nothing seems to work.  I was not able to find any relevant information on what might be the issue.

### Steps To Reproduce

1. Install Teslamate Unraid with correct MQTT credentials
2. Log in to Teslamate

### Relevant log output

```shell
2023-11-29 14:24:33.963 [warning] MQTT publishing failed: :timeout
2023-11-29 14:24:33.963 [warning] MQTT publishing failed: :timeout
2023-11-29 14:24:33.963 [warning] MQTT publishing failed: :timeout
2023-11-29 14:24:33.963 [warning] MQTT publishing failed: :timeout
2023-11-29 14:24:33.963 [warning] MQTT publishing failed: :timeout
2023-11-29 14:24:33.963 [warning] MQTT publishing failed: :timeout
2023-11-29 14:24:33.963 [warning] MQTT publishing failed: :timeout
2023-11-29 14:24:33.964 [warning] MQTT publishing failed: :timeout
2023-11-29 14:24:33.964 [warning] MQTT publishing failed: :timeout
2023-11-29 14:24:33.964 [warning] MQTT publishing failed: :timeout
2023-11-29 14:24:38.463 [error] GenServer TeslaMate.Mqtt.Publisher terminating
** (WithClauseError) no with clause matching: {:error, :timeout}
    (tortoise 0.10.0) lib/tortoise.ex:269: Tortoise.publish/4
    (teslamate 1.28.2) lib/teslamate/mqtt/publisher.ex:41: TeslaMate.Mqtt.Publisher.handle_call/3
    (stdlib 5.1.1) gen_server.erl:1113: :gen_server.try_handle_call/4
    (stdlib 5.1.1) gen_server.erl:1142: :gen_server.handle_msg/6
    (stdlib 5.1.1) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.3201.0>): {:publish, "teslamate/cars/1/usable_battery_level", "79", [retain: true, qos: 1]}
2023-11-29 14:24:38.464 [error] Task #PID<0.3222.0> started from #PID<0.3198.0> terminating
** (stop) exited in: GenServer.call(TeslaMate.Mqtt.Publisher, {:publish, "teslamate/cars/1/trim_badging", "P74D", [retain: true, qos: 1]}, 10000)
    ** (EXIT) an exception was raised:
        ** (WithClauseError) no with clause matching: {:error, :timeout}
            (tortoise 0.10.0) lib/tortoise.ex:269: Tortoise.publish/4
            (teslamate 1.28.2) lib/teslamate/mqtt/publisher.ex:41: TeslaMate.Mqtt.Publisher.handle_call/3
            (stdlib 5.1.1) gen_server.erl:1113: :gen_server.try_handle_call/4
            (stdlib 5.1.1) gen_server.erl:1142: :gen_server.handle_msg/6
            (stdlib 5.1.1) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
    (elixir 1.15.7) lib/gen_server.ex:1074: GenServer.call/3
    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
    (elixir 1.15.7) lib/task/supervised.ex:36: Task.Supervised.reply/4
Function: &:erlang.apply/2
    Args: [#Function<4.102219062/1 in TeslaMate.Mqtt.PubSub.VehicleSubscriber.handle_info/2>, [trim_badging: "P74D"]]
2023-11-29 14:24:38.464 [error] Task #PID<0.3227.0> started from #PID<0.3198.0> terminating
** (stop) exited in: GenServer.call(TeslaMate.Mqtt.Publisher, {:publish, "teslamate/cars/1/latitude", "42.098268", [retain: true, qos: 1]}, 10000)
    ** (EXIT) an exception was raised:
        ** (WithClauseError) no with clause matching: {:error, :timeout}
            (tortoise 0.10.0) lib/tortoise.ex:269: Tortoise.publish/4
            (teslamate 1.28.2) lib/teslamate/mqtt/publisher.ex:41: TeslaMate.Mqtt.Publisher.handle_call/3
            (stdlib 5.1.1) gen_server.erl:1113: :gen_server.try_handle_call/4
            (stdlib 5.1.1) gen_server.erl:1142: :gen_server.handle_msg/6
            (stdlib 5.1.1) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
    (elixir 1.15.7) lib/gen_server.ex:1074: GenServer.call/3
    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
    (elixir 1.15.7) lib/task/supervised.ex:36: Task.Supervised.reply/4
Function: &:erlang.apply/2
    Args: [#Function<4.102219062/1 in TeslaMate.Mqtt.PubSub.VehicleSubscriber.handle_info/2>, [latitude: Decimal.new("42.098268")]]
2023-11-29 14:24:38.464 [error] Task #PID<0.3228.0> started from #PID<0.3198.0> terminating
```

### Type of installation

Docker

### Version

v1.28.2

**Comment by parkr** [comment]
I think this would be better as a Discussion since MQTT works fine for most folks, so it's not a bug.

My recommendation would be to use `lsof` to ensure that MQTT is listening on the correct `host:port`. That anonymous connections aren't working either tells me that it's a problem with your Teslamate accessing that port at the given host name (and not authentication).

**Comment by brianmay** [comment]
Wonder if Mosquito is connecting in the first place. Unfortunately the logs above are insufficient to determine this. We need to see the logs immediately after starting Teslamate.

**Comment by BSkando** [comment]
Good call on the Discussion part, sorry about that.

Here is the beginning of the log.

`23-11-29 16:30:17.653 [info] POST https://auth.tesla.com/oauth2/v3/token -> 200 (981.830 ms)
2023-11-29 16:30:17.653 [info] Refreshed api tokens
2023-11-29 16:30:17.666 [info] Scheduling token refresh in 6 h
2023-11-29 16:30:17.667 [info] Running TeslaMateWeb.Endpoint with cowboy 2.10.0 at :::4000 (http)
2023-11-29 16:30:17.668 [info] Access TeslaMateWeb.Endpoint at http://localhost
2023-11-29 16:30:17.996 [info] Starting logger for 'Car'
2023-11-29 16:30:18.156 car_id=1 [info] Start / :offline
2023-11-29 16:30:19.845 [info] tzdata release in place is from a file last modified Fri, 22 Oct 2021 02:20:47 GMT. Release file on server was last modified Tue, 28 Mar 2023 20:25:39 GMT.
2023-11-29 16:30:20.237 [info] Tzdata has updated the release from 2021e to 2023c
2023-11-29 16:30:23.157 [warning] MQTT publishing failed: :timeout
2023-11-29 16:30:23.157 [warning] MQTT publishing failed: :timeout
2023-11-29 16:30:23.157 [warning] MQTT publishing failed: :timeout
2023-11-29 16:30:23.157 [warning] MQTT publishing failed: :timeout
2023-11-29 16:30:23.157 [warning] MQTT publishing failed: :timeout
2023-11-29 16:30:23.157 [warning] MQTT publishing failed: :timeout
2023-11-29 16:30:23.157 [warning] MQTT publishing failed: :timeout
2023-11-29 16:30:23.157 [warning] MQTT publishing failed: :timeout
2023-11-29 16:30:23.157 [warning] MQTT publishing failed: :timeout
2023-11-29 16:30:23.157 [warning] MQTT publishing failed: :timeout
2023-11-29 16:30:27.657 [error] GenServer TeslaMate.Mqtt.Publisher terminating
** (WithClauseError) no with clause matching: {:error, :timeout}'
