### ISSUE TITLE
Docker update error while installing 1.28.5 (from 1.28.3)

### ISSUE THREAD

**Issue by Edenglish92** [teslamate-org/teslamate#3878]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Docker-compose up -d ending with an error while trying to update to 1.28.5 (from 1.28.3). 
I checked that docker is up-to-date (26.1.1), existing issue found.

TERMINAL:
docker-compose pull
Pulling database  ... done
Pulling teslamate ... done
Pulling grafana   ... done
Pulling mosquitto ... done
Pulling proxy     ... done

docker-compose up -d
Recreating d129d22f1aff_teslamate_database_1 ...
Recreating 767e6ff2ae17_teslamate_mosquitto_1 ...
Recreating f287e44348be_teslamate_grafana_1   ...
Starting teslamate_proxy_1                    ...

ERROR: for d129d22f1aff_teslamate_database_1  'ContainerConfig'

ERROR: for 767e6ff2ae17_teslamate_mosquitto_1  'ContainerConfig'

Starting teslamate_proxy_1                    ... done

ERROR: for database  'ContainerConfig'

ERROR: for mosquitto  'ContainerConfig'

ERROR: for grafana  'ContainerConfig'
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 203, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3/dist-packages/compose/metrics/decorator.py", line 18, in wrapper
    result = fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1186, in up
    to_attach = up(False)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1166, in up
    return self.project.up(
  File "/usr/lib/python3/dist-packages/compose/project.py", line 697, in up
    results, errors = parallel.parallel_execute(
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 108, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 206, in producer
    result = func(obj)
  File "/usr/lib/python3/dist-packages/compose/project.py", line 679, in do
    return service.execute_convergence_plan(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 579, in execute_convergence_plan
    return self._execute_convergence_recreate(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 499, in _execute_convergence_recreate
    containers, errors = parallel_execute(
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 108, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 206, in producer
    result = func(obj)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 494, in recreate
    return self.recreate_container(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 612, in recreate_container
    new_container = self.create_container(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 330, in create_container
    container_options = self._get_container_create_options(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 921, in _get_container_create_options
    container_options, override_options = self._build_container_volume_options(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 960, in _build_container_volume_options
    binds, affinity = merge_volume_bindings(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 1548, in merge_volume_bindings
    old_volumes, old_mounts = get_container_data_volumes(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 1579, in get_container_data_volumes
    container.image_config['ContainerConfig'].get('Volumes') or {}
KeyError: 'ContainerConfig'

Thanks for your help 

### Relevant log output

```shell
Logs are copied above
```

### Type of installation

Docker

### Version

v1.28.3

**Comment by JakobLichterfeld** [comment]
Thanks for reporting.

You are using a deprecated version of docker-compose. 
docker compose (without - is the correct one)

see also our [documentation](https://docs.teslamate.org/docs/upgrading):

> If you are using docker-compose, you are using Docker Compose v1, which has been deprecated. Docker Compose commands refer to Docker Compose v2. Consider upgrading your docker setup, see [Migrate to Compose V2](https://docs.docker.com/compose/migrate/)

**Comment by Edenglish92** [comment]
Thanks very much for your help @JakobLichterfeld !
