### ISSUE TITLE
Teslamate crashes after upgrading to 1.29.0

### ISSUE THREAD

**Issue by rog0978** [teslamate-org/teslamate#3897]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Teslamate won't come up after upgrading to 1.29.0

### Expected Behavior

Teslamate starting

### Steps To Reproduce

Install V1.29.0 via docker compose

### Relevant log output

```shell
teslamate-1  | 2024-05-20 11:43:03.273 [info] Migrations already up
teslamate-1  | 2024-05-20 11:43:08.313 [info] No tzdata release files found in custom data dir. Copying release file from tzdata priv dir.
teslamate-1  | 2024-05-20 11:43:08.549 [info] System Info: Erlang/OTP 26 (jit)
teslamate-1  | 2024-05-20 11:43:08.550 [info] Version: 1.29.0
teslamate-1  | 2024-05-20 11:43:08.681 [notice] Application teslamate exited: TeslaMate.Application.start(:normal, []) returned an error: shutdown: failed to start child: TeslaMate.Api
teslamate-1  |     ** (EXIT) an exception was raised:
teslamate-1  |         ** (MatchError) no match of right hand side value: "https://auth.tesla.com/oauth2/v3"
teslamate-1  |             (teslamate 1.29.0) lib/tesla_api/auth/refresh.ex:12: TeslaApi.Auth.Refresh.refresh/1
teslamate-1  |             (teslamate 1.29.0) lib/teslamate/api.ex:220: TeslaMate.Api.refresh_tokens/1
teslamate-1  |             (teslamate 1.29.0) lib/teslamate/api.ex:116: TeslaMate.Api.init/1
teslamate-1  |             (stdlib 5.2) gen_server.erl:980: :gen_server.init_it/2
teslamate-1  |             (stdlib 5.2) gen_server.erl:935: :gen_server.init_it/6
teslamate-1  |             (stdlib 5.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
teslamate-1  | Kernel pid terminated (application_controller) ("{application_start_failure,teslamate,{{shutdown,{failed_to_start_child,'Elixir.TeslaMate.Api',{{badmatch,<<\"https://auth.tesla.com/oauth2/v3\">>},[{'Elixir.TeslaApi.Auth.Refresh',refresh,1,[{file,\"lib/tesla_api/auth/refresh.ex\"},{line,12}]},{'Elixir.TeslaMate.Api',refresh_tokens,1,[{file,\"lib/teslamate/api.ex\"},{line,220}]},{'Elixir.TeslaMate.Api',init,1,[{file,\"lib/teslamate/api.ex\"},{line,116}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,980}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,935}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,241}]}]}}},{'Elixir.TeslaMate.Application',start,[normal,[]]}}}")
teslamate-1  | 
teslamate-1  | Crash dump is being written to: erl_crash.dump...done
teslamate-1  | 2024-05-20 11:43:14.020 [info] Migrations already up
```

### Type of installation

Docker

### Version

V1.29.0

**Comment by JakobLichterfeld** [comment]
Sorry, #3866 is breaking backwards compatibility, v1.29.1 will be releases in few minutes

**Comment by JakobLichterfeld** [comment]
solved by [v1.29.1](https://github.com/teslamate-org/teslamate/releases/tag/v1.29.1)
