### ISSUE TITLE
error with backup and restore like description

### ISSUE THREAD

**Issue by bff0172** [teslamate-org/teslamate#4152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

after creating teslamate.bck I get an error when doing a restore:

ERROR:  invalid input syntax for type numeric: ""
CONTEXT:  COPY positions, line 1495091, column tpms_pressure_fl: ""

### Relevant log output

```shell
b@raspberrypi:~/tesla $ docker compose logs teslamate
WARN[0000] /home/b/tesla/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
teslamate-1  | 2024-08-22 12:07:47.198 [info] Migrations already up
teslamate-1  | 2024-08-22 12:07:49.335 [info] No tzdata release files found in custom data dir. Copying release file from tzdata priv dir.
teslamate-1  | 2024-08-22 12:07:49.421 [info] System Info: Erlang/OTP 26 (jit)
teslamate-1  | 2024-08-22 12:07:49.421 [info] Version: 1.30.1
teslamate-1  | 2024-08-22 12:07:49.460 [info] Running TeslaMateWeb.Endpoint with cowboy 2.10.0 at :::4000 (http)
teslamate-1  | 2024-08-22 12:07:49.460 [info] Access TeslaMateWeb.Endpoint at http://localhost
teslamate-1  | 2024-08-22 12:07:49.465 [info] MQTT connection has been established
teslamate-1  | 2024-08-22 12:07:50.992 [info] GET /sign_in
teslamate-1  | 2024-08-22 12:07:50.999 [info] Sent 200 in 6ms
teslamate-1  | 2024-08-22 12:07:53.069 [info] tzdata release in place is from a file last modified Fri, 22 Oct 2021 02:20:47 GMT. Release file on server was last modified Thu, 01 Feb 2024 18:40:48 GMT.
teslamate-1  | 2024-08-22 12:07:54.735 [info] Tzdata has updated the release from 2021e to 2024a
teslamate-1  | 2024-08-22 12:08:23.951 [info] GET /
teslamate-1  | 2024-08-22 12:08:23.952 [info] Sent 302 in 1ms
teslamate-1  | 2024-08-22 12:08:24.072 [info] GET /sign_in
teslamate-1  | 2024-08-22 12:08:24.075 [info] Sent 200 in 2ms
teslamate-1  | 2024-08-22 12:08:55.212 [error] POST https://auth.tesla.com/oauth2/v3/token -> 401 (458.990 ms)
teslamate-1  | 2024-08-22 12:09:59.173 [error] POST https://auth.tesla.com/oauth2/v3/token -> 401 (444.374 ms)
teslamate-1  | 2024-08-22 12:10:15.337 [error] POST https://auth.tesla.com/oauth2/v3/token -> 401 (423.968 ms)
teslamate-1  | 2024-08-22 12:13:33.427 [notice] SIGTERM received - shutting down
teslamate-1  |
teslamate-1  | 2024-08-22 12:13:33.429 [info] Shutting down 2 sockets in 1 rounds of 2000ms
teslamate-1  | 2024-08-22 12:13:57.474 [info] == Running 20190330150000 TeslaMate.Repo.Migrations.CreateCar.change/0 forward
teslamate-1  | 2024-08-22 12:13:57.477 [info] create table cars
teslamate-1  | ** (Postgrex.Error) ERROR 42P07 (duplicate_table) relation "cars" already exists
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1047: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate-1  |     (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1154: Ecto.Adapters.SQL.execute_ddl/4
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/migration/runner.ex:327: Ecto.Migration.Runner.log_and_execute_ddl/3
teslamate-1  |     (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/migration/runner.ex:290: Ecto.Migration.Runner.perform_operation/3
teslamate-1  |     (stdlib 5.2.3) timer.erl:270: :timer.tc/2
teslamate-1  | 2024-08-22 12:14:05.173 [info] == Running 20190330150000 TeslaMate.Repo.Migrations.CreateCar.change/0 forward
teslamate-1  | 2024-08-22 12:14:05.175 [info] create table cars
teslamate-1  | ** (Postgrex.Error) ERROR 42P07 (duplicate_table) relation "cars" already exists
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1047: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate-1  |     (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1154: Ecto.Adapters.SQL.execute_ddl/4
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/migration/runner.ex:327: Ecto.Migration.Runner.log_and_execute_ddl/3
teslamate-1  |     (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/migration/runner.ex:290: Ecto.Migration.Runner.perform_operation/3
teslamate-1  |     (stdlib 5.2.3) timer.erl:270: :timer.tc/2
teslamate-1  | 2024-08-22 12:14:09.018 [info] == Running 20190330150000 TeslaMate.Repo.Migrations.CreateCar.change/0 forward
teslamate-1  | 2024-08-22 12:14:09.021 [info] create table cars
teslamate-1  | ** (Postgrex.Error) ERROR 42P07 (duplicate_table) relation "cars" already exists
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1047: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate-1  |     (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1154: Ecto.Adapters.SQL.execute_ddl/4
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/migration/runner.ex:327: Ecto.Migration.Runner.log_and_execute_ddl/3
teslamate-1  |     (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/migration/runner.ex:290: Ecto.Migration.Runner.perform_operation/3
teslamate-1  |     (stdlib 5.2.3) timer.erl:270: :timer.tc/2
teslamate-1  | 2024-08-22 12:14:12.892 [info] == Running 20190330150000 TeslaMate.Repo.Migrations.CreateCar.change/0 forward
teslamate-1  | 2024-08-22 12:14:12.894 [info] create table cars
teslamate-1  | ** (Postgrex.Error) ERROR 42P07 (duplicate_table) relation "cars" already exists
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1047: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate-1  |     (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1154: Ecto.Adapters.SQL.execute_ddl/4
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/migration/runner.ex:327: Ecto.Migration.Runner.log_and_execute_ddl/3
teslamate-1  |     (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/migration/runner.ex:290: Ecto.Migration.Runner.perform_operation/3
teslamate-1  |     (stdlib 5.2.3) timer.erl:270: :timer.tc/2
teslamate-1  | 2024-08-22 12:14:17.106 [info] == Running 20190330150000 TeslaMate.Repo.Migrations.CreateCar.change/0 forward
teslamate-1  | 2024-08-22 12:14:17.109 [info] create table cars
teslamate-1  | ** (Postgrex.Error) ERROR 42P07 (duplicate_table) relation "cars" already exists
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1047: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate-1  |     (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1154: Ecto.Adapters.SQL.execute_ddl/4
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/migration/runner.ex:327: Ecto.Migration.Runner.log_and_execute_ddl/3
teslamate-1  |     (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/migration/runner.ex:290: Ecto.Migration.Runner.perform_operation/3
teslamate-1  |     (stdlib 5.2.3) timer.erl:270: :timer.tc/2
teslamate-1  | 2024-08-22 12:14:22.149 [info] == Running 20190330150000 TeslaMate.Repo.Migrations.CreateCar.change/0 forward
teslamate-1  | 2024-08-22 12:14:22.151 [info] create table cars
teslamate-1  | ** (Postgrex.Error) ERROR 42P07 (duplicate_table) relation "cars" already exists
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1047: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate-1  |     (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1154: Ecto.Adapters.SQL.execute_ddl/4
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/migration/runner.ex:327: Ecto.Migration.Runner.log_and_execute_ddl/3
teslamate-1  |     (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/migration/runner.ex:290: Ecto.Migration.Runner.perform_operation/3
teslamate-1  |     (stdlib 5.2.3) timer.erl:270: :timer.tc/2
teslamate-1  | 2024-08-22 12:14:28.896 [info] == Running 20190330150000 TeslaMate.Repo.Migrations.CreateCar.change/0 forward
teslamate-1  | 2024-08-22 12:14:28.898 [info] create table cars
teslamate-1  | ** (Postgrex.Error) ERROR 42P07 (duplicate_table) relation "cars" already exists
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1047: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate-1  |     (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1154: Ecto.Adapters.SQL.execute_ddl/4
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/migration/runner.ex:327: Ecto.Migration.Runner.log_and_execute_ddl/3
teslamate-1  |     (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/migration/runner.ex:290: Ecto.Migration.Runner.perform_operation/3
teslamate-1  |     (stdlib 5.2.3) timer.erl:270: :timer.tc/2
teslamate-1  | 2024-08-22 12:14:38.742 [info] == Running 20190330150000 TeslaMate.Repo.Migrations.CreateCar.change/0 forward
teslamate-1  | 2024-08-22 12:14:38.744 [info] create table cars
teslamate-1  | ** (Postgrex.Error) ERROR 42P07 (duplicate_table) relation "cars" already exists
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1047: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate-1  |     (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1154: Ecto.Adapters.SQL.execute_ddl/4
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/migration/runner.ex:327: Ecto.Migration.Runner.log_and_execute_ddl/3
teslamate-1  |     (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/migration/runner.ex:290: Ecto.Migration.Runner.perform_operation/3
teslamate-1  |     (stdlib 5.2.3) timer.erl:270: :timer.tc/2
teslamate-1  | 2024-08-22 12:14:55.011 [info] == Running 20190330150000 TeslaMate.Repo.Migrations.CreateCar.change/0 forward
teslamate-1  | 2024-08-22 12:14:55.013 [info] create table cars
teslamate-1  | ** (Postgrex.Error) ERROR 42P07 (duplicate_table) relation "cars" already exists
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1047: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate-1  |     (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1154: Ecto.Adapters.SQL.execute_ddl/4
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/migration/runner.ex:327: Ecto.Migration.Runner.log_and_execute_ddl/3
teslamate-1  |     (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/migration/runner.ex:290: Ecto.Migration.Runner.perform_operation/3
teslamate-1  |     (stdlib 5.2.3) timer.erl:270: :timer.tc/2
teslamate-1  | 2024-08-22 12:15:24.096 [info] == Running 20190330150000 TeslaMate.Repo.Migrations.CreateCar.change/0 forward
teslamate-1  | 2024-08-22 12:15:24.098 [info] create table cars
teslamate-1  | ** (Postgrex.Error) ERROR 42P07 (duplicate_table) relation "cars" already exists
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1047: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate-1  |     (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1154: Ecto.Adapters.SQL.execute_ddl/4
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/migration/runner.ex:327: Ecto.Migration.Runner.log_and_execute_ddl/3
teslamate-1  |     (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/migration/runner.ex:290: Ecto.Migration.Runner.perform_operation/3
teslamate-1  |     (stdlib 5.2.3) timer.erl:270: :timer.tc/2
teslamate-1  | 2024-08-22 12:16:18.825 [info] == Running 20190330150000 TeslaMate.Repo.Migrations.CreateCar.change/0 forward
teslamate-1  | 2024-08-22 12:16:18.827 [info] create table cars
teslamate-1  | ** (Postgrex.Error) ERROR 42P07 (duplicate_table) relation "cars" already exists
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1047: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate-1  |     (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1154: Ecto.Adapters.SQL.execute_ddl/4
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/migration/runner.ex:327: Ecto.Migration.Runner.log_and_execute_ddl/3
teslamate-1  |     (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/migration/runner.ex:290: Ecto.Migration.Runner.perform_operation/3
teslamate-1  |     (stdlib 5.2.3) timer.erl:270: :timer.tc/2
teslamate-1  | 2024-08-22 12:17:22.267 [info] == Running 20190330150000 TeslaMate.Repo.Migrations.CreateCar.change/0 forward
teslamate-1  | 2024-08-22 12:17:22.269 [info] create table cars
teslamate-1  | ** (Postgrex.Error) ERROR 42P07 (duplicate_table) relation "cars" already exists
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1047: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate-1  |     (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1154: Ecto.Adapters.SQL.execute_ddl/4
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/migration/runner.ex:327: Ecto.Migration.Runner.log_and_execute_ddl/3
teslamate-1  |     (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/migration/runner.ex:290: Ecto.Migration.Runner.perform_operation/3
teslamate-1  |     (stdlib 5.2.3) timer.erl:270: :timer.tc/2
teslamate-1  | 2024-08-22 12:18:25.799 [info] == Running 20190330150000 TeslaMate.Repo.Migrations.CreateCar.change/0 forward
teslamate-1  | 2024-08-22 12:18:25.801 [info] create table cars
teslamate-1  | ** (Postgrex.Error) ERROR 42P07 (duplicate_table) relation "cars" already exists
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1047: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate-1  |     (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1154: Ecto.Adapters.SQL.execute_ddl/4
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/migration/runner.ex:327: Ecto.Migration.Runner.log_and_execute_ddl/3
teslamate-1  |     (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
teslamate-1  |     (ecto_sql 3.10.2) lib/ecto/migration/runner.ex:290: Ecto.Migration.Runner.perform_operation/3
teslamate-1  |     (stdlib 5.2.3) timer.erl:270: :timer.tc/2
```

### Type of installation

Docker

### Version

v1.30.1

**Comment by JakobLichterfeld** [comment]
Thanks for reporting.
As you did not specify how you performed your backup or restore and your logs indicate you didn't follow the documentation, please do so: https://docs.teslamate.org/docs/maintenance/backup_restore

**Comment by bff0172** [comment]
ok I followed the doc again, now the import is done without errors or warning - but I have the issue that I cannot login to new Grafana instance - should it be the same like the old one?

**Comment by JakobLichterfeld** [comment]
> ok I followed the doc again, now the import is done without errors or warning

Awesome


> but I have the issue that I cannot login to new Grafana instance - should it be the same like the old one?

Not sure what you mean. The standard docker installation does not have any authentication setup. 
So it depends on your `docker-compose.yml` file

**Comment by bff0172** [comment]
> > but I have the issue that I cannot login to new Grafana instance - should it be the same like the old one?
> 
> Not sure what you mean. The standard docker installation does not have any authentication setup. So it depends on your `docker-compose.yml` file

I think it's too hot actual - means: Layer8 problem ;-)
I thought I have to use my old username/password - with default admin (without password) it works (of course).
Thanks! and sorry for the stupid issue...

**Comment by JakobLichterfeld** [comment]
> it works

Perfect and good to hear. We hope you continue to enjoy TeslaMate.

**Comment by wgemini** [comment]
@JakobLichterfeld  I am hitting the same issue. I tried to follow the instructions in the backup/restore page:

```
docker compose exec -T database psql -U teslamate teslamate << .

DROP SCHEMA public CASCADE;

CREATE SCHEMA public;

CREATE EXTENSION cube WITH SCHEMA public;

CREATE EXTENSION earthdistance WITH SCHEMA public;

.

docker compose exec -T database psql -U teslamate -d teslamate < backups/20251019020001-database.bck
```

Database was restored successfully with no error message, but I am still getting the same error:

```
2025-10-19 17:32:02.451 [info] == Running 20190330150000 TeslaMate.Repo.Migrations.CreateCar.change/0 forward
2025-10-19 17:32:02.453 [info] create table cars
** (Postgrex.Error) ERROR 42P07 (duplicate_table) relation "cars" already exists
    (ecto_sql 3.13.2) lib/ecto/adapters/sql.ex:1098: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.17.3) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
    (ecto_sql 3.13.2) lib/ecto/adapters/sql.ex:1219: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.13.2) lib/ecto/migration/runner.ex:348: Ecto.Migration.Runner.log_and_execute_ddl/3
    (elixir 1.17.3) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
    (ecto_sql 3.13.2) lib/ecto/migration/runner.ex:311: Ecto.Migration.Runner.perform_operation/3
    (stdlib 5.2.3.4) timer.erl:270: :timer.tc/2
2025-10-19 17:33:04.911 [info] == Running 20190330150000 TeslaMate.Repo.Migrations.CreateCar.change/0 forward
2025-10-19 17:33:04.913 [info] create table cars
** (Postgrex.Error) ERROR 42P07 (duplicate_table) relation "cars" already exists
    (ecto_sql 3.13.2) lib/ecto/adapters/sql.ex:1098: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.17.3) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
    (ecto_sql 3.13.2) lib/ecto/adapters/sql.ex:1219: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.13.2) lib/ecto/migration/runner.ex:348: Ecto.Migration.Runner.log_and_execute_ddl/3
    (elixir 1.17.3) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
    (ecto_sql 3.13.2) lib/ecto/migration/runner.ex:311: Ecto.Migration.Runner.perform_operation/3
    (stdlib 5.2.3.4) timer.erl:270: :timer.tc/2
```
I verified that there is public.cars table in my database. Any suggestions?

**Comment by JakobLichterfeld** [comment]
> Any suggestions?

Checking your docker-compose.yml, ensure the commands execute succesfully

**Comment by wgemini** [comment]
@JakobLichterfeld  Thanks. Found the problem. My last 4 days of backup was incomplete (probably due to the recent collation change issue). Restored to a previous backup worked. I think the doc for the backup should warn users to make sure the backup was successful. Either to redirect the error to a log or make sure "PostgreSQL database dump complete" is part of the backup file.
