### ISSUE TITLE
home-assistant template errors

### ISSUE THREAD

**Issue by brianmay** [teslamate-org/teslamate#4247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Is starting to urk me that home-assistant is generating non-stop errors on my system. This aren't actually "errors" in the sense of something going wrong, just annoying to look at in the logs.

It would look appear the biggest culprit is the teslamate recommended config from https://docs.teslamate.org/docs/integrations/home_assistant/

Unfortunately, my home-assistant knowledge in fixing these isn't particularly great.

(on a semi-related note, would be really good id teslamate could send out discovery messages so that this can be auto-configured - see https://www.home-assistant.io/integrations/mqtt#mqtt-discovery - assuming this is possible)

### Expected Behavior

No errors

### Steps To Reproduce

Run home-assistant after adding settings from https://docs.teslamate.org/docs/integrations/home_assistant/

### Relevant log output

```shell
Oct 07 15:10:43 iot2 homeassistant[107792]: 2024-10-07 15:10:43.127 WARNING (MainThread) [homeassistant.components.mqtt.mixins] TypeError: Object of type LoggingUndefined is not JSON serializable rendering template for entity 'device_tracker.tesla_active_route_location', template: '{{ value_json.location | tojson }}' and payload: {"error":"No active route available"}
Oct 07 15:10:43 iot2 homeassistant[107792]: 2024-10-07 15:10:43.127 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'destination' when rendering '{{ value_json.destination }}'
Oct 07 15:10:43 iot2 homeassistant[107792]: 2024-10-07 15:10:43.127 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'energy_at_arrival' when rendering '{{ value_json.energy_at_arrival }}'
Oct 07 15:10:43 iot2 homeassistant[107792]: 2024-10-07 15:10:43.128 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'miles_to_arrival' when rendering '{{ value_json.miles_to_arrival }}'
Oct 07 15:10:43 iot2 homeassistant[107792]: 2024-10-07 15:10:43.128 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'minutes_to_arrival' when rendering '{{ value_json.minutes_to_arrival }}'
Oct 07 15:10:43 iot2 homeassistant[107792]: 2024-10-07 15:10:43.128 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'traffic_minutes_delay' when rendering '{{ value_json.traffic_minutes_delay }}'
Oct 07 15:10:45 iot2 homeassistant[107792]: 2024-10-07 15:10:45.723 ERROR (Thread-9) [pychromecast.socket_client] [Dining room TV(192.168.5.192):8009] Failed to connect to service MDNSServiceInfo(name='Chromecast-c6be7577e2d8f2215bf00c76a003635b._googlecast._tcp.local.'), retrying in 5.0s
Oct 07 15:10:46 iot2 homeassistant[107792]: 2024-10-07 15:10:46.176 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({{ (states('sensor.tesla_active_route_distance_to_arrival_mi') | float * 1.609344) | round(2) }}) renders=2>
```

```
Oct 07 15:10:46 iot2 homeassistant[107792]: homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ (states('sensor.tesla_active_route_distance_to_arrival_mi') | float * 1.609344) | round(2) }}' but no default was specified
Oct 07 15:10:46 iot2 homeassistant[107792]: 2024-10-07 15:10:46.179 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ (states('sensor.tesla_active_route_distance_to_arrival_mi') | float * 1.609344) | round(2) }}' but no default was specified') while processing template 'Template<template=({{ (states('sensor.tesla_active_route_distance_to_arrival_mi') | float * 1.609344) | round(2) }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.tesla_active_route_distance_to_arrival_km'
```
```


### Screenshots

_No response_

### Additional data

_No response_

### Type of installation

Manual

### Version

latest

**Comment by JakobLichterfeld** [comment]
Nice find. Not using home-assistant atm. From what I see, this only occurs when you do not have an active navigation destination set in car. Then the MQTT values are empty.
So the "error" handling could be improved.

@longzheng: can you please take a look into it? You introduced it with #3657. Ty.

**Comment by longzheng** [comment]
I think https://github.com/teslamate-org/teslamate/pull/3923 is more relevant to this issue since that's where I defined/added the Home Assistant sensors.

I thought I had already handled this with the `availability` attribute on `device_tracker`

```yaml
- device_tracker:
    name: Active route location
    object_id: tesla_active_route_location
    unique_id: teslamate_1_active_route_location
    availability: &teslamate_active_route_availability
      - topic: "teslamate/cars/1/active_route"
        value_template: "{{ 'offline' if value_json.error else 'online' }}"
    device: *teslamate_device_info
    json_attributes_topic: "teslamate/cars/1/active_route"
    json_attributes_template: "{{ value_json.location | tojson }}"
    icon: mdi:crosshairs-gps
```

And then each sensor references the `availability: *teslamate_active_route_availability`

```
- sensor:
    name: Active route energy at arrival
    object_id: tesla_active_route_energy_at_arrival
    unique_id: teslamate_1_active_route_energy_at_arrival
    availability: *teslamate_active_route_availability
    device: *teslamate_device_info
    state_topic: "teslamate/cars/1/active_route"
    value_template: "{{ value_json.energy_at_arrival }}"
    unit_of_measurement: "%"
    icon: mdi:battery-80
```

But my Home Assistant sensor experience is very limited so maybe that's not right.

**Comment by longzheng** [comment]
OK after a bit more digging, it looks like `availability` has no impact on whether the MQTT integration tries to parse the `json_attributes`, it will try to parse it even if the device is unavailable from the `availability.`

I think an alternative is to define a conditional `json_attributes_template` like

```yaml
- device_tracker:
    name: Active route location
    object_id: tesla_active_route_location
    unique_id: teslamate_1_active_route_location
    availability: &teslamate_active_route_availability
      - topic: "teslamate/cars/1/active_route"
        value_template: "{{ 'offline' if value_json.error else 'online' }}"
    device: *teslamate_device_info
    json_attributes_topic: "teslamate/cars/1/active_route"
    json_attributes_template: >
      {% if not value_json.error and value_json.location %}
        {{ value_json.location | tojson }}
      {% else %}
        {}
      {% endif %}
    icon: mdi:crosshairs-gps
```

Based on my testing this stops the warning.

And the other sensors would have something like
```yaml
- sensor:
    name: Active route destination
    object_id: tesla_active_route_destination
    unique_id: teslamate_1_active_route_destination
    availability: *teslamate_active_route_availability
    device: *teslamate_device_info
    state_topic: "teslamate/cars/1/active_route"
    value_template: >
      {% if not value_json.error and value_json.destination %}
        {{ value_json.destination }}
      {% endif %}
    icon: mdi:map-marker

- sensor:
    name: Active route energy at arrival
    object_id: tesla_active_route_energy_at_arrival
    unique_id: teslamate_1_active_route_energy_at_arrival
    availability: *teslamate_active_route_availability
    device: *teslamate_device_info
    state_topic: "teslamate/cars/1/active_route"
    value_template: >
      {% if not value_json.error and value_json.energy_at_arrival %}
        {{ value_json.energy_at_arrival }}
      {% endif %}
    unit_of_measurement: "%"
    icon: mdi:battery-80

- sensor:
    name: Active route distance to arrival (mi)
    object_id: tesla_active_route_distance_to_arrival_mi
    unique_id: teslamate_1_active_route_distance_to_arrival_mi
    availability: *teslamate_active_route_availability
    device: *teslamate_device_info
    state_topic: "teslamate/cars/1/active_route"
    value_template: >
      {% if not value_json.error and value_json.miles_to_arrival %}
        {{ value_json.miles_to_arrival }}
      {% endif %}
    unit_of_measurement: mi
    icon: mdi:map-marker-distance

- sensor:
    name: Active route minutes to arrival
    object_id: tesla_active_route_minutes_to_arrival
    unique_id: teslamate_1_active_route_minutes_to_arrival
    availability: *teslamate_active_route_availability
    device: *teslamate_device_info
    state_topic: "teslamate/cars/1/active_route"
    value_template: >
      {% if not value_json.error and value_json.minutes_to_arrival %}
        {{ value_json.minutes_to_arrival }}
      {% endif %}
    unit_of_measurement: min
    icon: mdi:clock-outline

- sensor:
    name: Active route traffic minutes delay
    object_id: tesla_active_route_traffic_minutes_delay
    unique_id: teslamate_1_active_route_traffic_minutes_delay
    availability: *teslamate_active_route_availability
    device: *teslamate_device_info
    state_topic: "teslamate/cars/1/active_route"
    value_template: >
      {% if not value_json.error and value_json.traffic_minutes_delay %}
        {{ value_json.traffic_minutes_delay }}
      {% endif %}
    unit_of_measurement: min
    icon: mdi:clock-alert-outline
```

**Comment by longzheng** [comment]
While we're on this topic I've also seen other actual errors reported by Home Assistant related to the Teslamate sensors

```
TemplateError('ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ (states('sensor.tesla_tpms_fl') | float * 14.50377) | round(2) }}' but no default was specified') while processing template 'Template<template=({{ (states('sensor.tesla_tpms_fl') | float * 14.50377) | round(2) }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.tesla_tpms_pressure_fl_psi'
TemplateError('ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ (states('sensor.tesla_tpms_fr') | float * 14.50377) | round(2) }}' but no default was specified') while processing template 'Template<template=({{ (states('sensor.tesla_tpms_fr') | float * 14.50377) | round(2) }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.tesla_tpms_pressure_fr_psi'
TemplateError('ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ (states('sensor.tesla_tpms_rl') | float * 14.50377) | round(2) }}' but no default was specified') while processing template 'Template<template=({{ (states('sensor.tesla_tpms_rl') | float * 14.50377) | round(2) }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.tesla_tpms_pressure_rl_psi'
TemplateError('ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ (states('sensor.tesla_tpms_rr') | float * 14.50377) | round(2) }}' but no default was specified') while processing template 'Template<template=({{ (states('sensor.tesla_tpms_rr') | float * 14.50377) | round(2) }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.tesla_tpms_pressure_rr_psi'
TemplateError('ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ (states('sensor.tesla_active_route_distance_to_arrival_mi') | float * 1.609344) | round(2) }}' but no default was specified') while processing template 'Template<template=({{ (states('sensor.tesla_active_route_distance_to_arrival_mi') | float * 1.609344) | round(2) }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.tesla_active_route_distance_to_arrival_km'
```

I believe these are related to the fact that it's trying to convert the sensor values from one unit to another (e.g. kilometre to miles) when the MQTT sensors have no state/unavailable.

I wonder if we should have some similar `availability_template` and conditional `value_template`

```yaml
    tesla_ideal_battery_range_mi:
      friendly_name: Ideal Range (mi)
      unit_of_measurement: mi
      icon_template: mdi:gauge
      availability_template: "{{ has_value('sensor.tesla_ideal_battery_range_km') }}"
      value_template: >
        {% if has_value('sensor.tesla_ideal_battery_range_km') %}
          {{ (states('sensor.tesla_ideal_battery_range_km') | float / 1.609344) | round(2) }}
        {% endif %}
```

**Comment by JakobLichterfeld** [comment]
> I think #3923 is more relevant to this issue since that's where I defined/added the Home Assistant sensors.

Yeah you are right.

> I think an alternative is to define a conditional `json_attributes_template` like

> Based on my testing this stops the warning.

Perfect.

@brianmay What do you think? Imo it is sufficient to handle it on Home Assistant side, only updating our docs.

**Comment by longzheng** [comment]
I'll test a bit more and open a PR for this.

**Comment by brianmay** [comment]
I think that solution needs expanding on:

```
Oct 08 09:00:56 iot2 homeassistant[118534]: homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'unavailable' when rendering template '{% if has_value('sensor.tesla_ideal_battery_range_km') %}
Oct 08 09:00:56 iot2 homeassistant[118534]:   {{ (states('sensor.tesla_active_route_distance_to_arrival_mi') | float * 1.609344) | round(2) }}
Oct 08 09:00:56 iot2 homeassistant[118534]: {% endif %}' but no default was specified
```

Guessing this means all the sensor values need to have an `else` clause.

I think updating the docs will be sufficient for now. Once some of these other issues are resolved I might look at auto discovery a bit more.

**Comment by longzheng** [comment]
> I think that solution needs expanding on:
> 
> 
> 
> ```
> 
> Oct 08 09:00:56 iot2 homeassistant[118534]: homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'unavailable' when rendering template '{% if has_value('sensor.tesla_ideal_battery_range_km') %}
> 
> Oct 08 09:00:56 iot2 homeassistant[118534]:   {{ (states('sensor.tesla_active_route_distance_to_arrival_mi') | float * 1.609344) | round(2) }}
> 
> Oct 08 09:00:56 iot2 homeassistant[118534]: {% endif %}' but no default was specified
> 
> ```
> 
> 
> 
> Guessing this means all the sensor values need to have an `else` clause.
> 

Not sure if a typo but it looks like the `tesla_ideal_battery_range_km` got mixed up with `tesla_active_route_distance_to_arrival_mi`

**Comment by brianmay** [comment]
Good catch.

Now getting this class of errors for all sensors:

```
Oct 08 09:15:50 iot2 homeassistant[119298]: ValueError: Sensor sensor.tesla_est_battery_range_mi has device class 'None', state class 'None' unit 'mi' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: '' (<class 'str'>)
```

**Comment by longzheng** [comment]
> Good catch.
> 
> Now getting this class of errors for all sensors:
> 
> ```
> Oct 08 09:15:50 iot2 homeassistant[119298]: ValueError: Sensor sensor.tesla_est_battery_range_mi has device class 'None', state class 'None' unit 'mi' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: '' (<class 'str'>)
> ```

I haven't seen any similar errors.

Just double checking if you modified the other sensors than the one I mentioned `tesla_ideal_battery_range_mi` since your error was for `tesla_est_battery_range_mi`.

Here's my full `sensor.yaml`

```yml
- platform: template
  sensors:
    tesla_est_battery_range_mi:
      friendly_name: Estimated Range (mi)
      unit_of_measurement: mi
      icon_template: mdi:gauge
      availability_template: "{{ has_value('sensor.tesla_est_battery_range_km') }}"
      value_template: >
        {% if has_value('sensor.tesla_est_battery_range_km') %}
          {{ (states('sensor.tesla_est_battery_range_km') | float / 1.609344) | round(2) }}
        {% endif %}

    tesla_rated_battery_range_mi:
      friendly_name: Rated Range (mi)
      unit_of_measurement: mi
      icon_template: mdi:gauge
      availability_template: "{{ has_value('sensor.tesla_rated_battery_range_km') }}"
      value_template: >
        {% if has_value('sensor.tesla_rated_battery_range_km') %}
          {{ (states('sensor.tesla_rated_battery_range_km') | float / 1.609344) | round(2) }}
        {% endif %}

    tesla_ideal_battery_range_mi:
      friendly_name: Ideal Range (mi)
      unit_of_measurement: mi
      icon_template: mdi:gauge
      availability_template: "{{ has_value('sensor.tesla_ideal_battery_range_km') }}"
      value_template: >
        {% if has_value('sensor.tesla_ideal_battery_range_km') %}
          {{ (states('sensor.tesla_ideal_battery_range_km') | float / 1.609344) | round(2) }}
        {% endif %}

    tesla_odometer_mi:
      friendly_name: Odometer (mi)
      unit_of_measurement: mi
      icon_template: mdi:counter
      availability_template: "{{ has_value('sensor.tesla_odometer') }}"
      value_template: >
        {% if has_value('sensor.tesla_odometer') %}
          {{ (states('sensor.tesla_odometer') | float / 1.609344) | round(2) }}
        {% endif %}

    tesla_speed_mph:
      friendly_name: Speed (MPH)
      unit_of_measurement: mph
      icon_template: mdi:speedometer
      availability_template: "{{ has_value('sensor.tesla_speed') }}"
      value_template: >
        {% if has_value('sensor.tesla_speed') %}
          {{ (states('sensor.tesla_speed') | float / 1.609344) | round(2) }}
        {% endif %}

    tesla_elevation_ft:
      friendly_name: Elevation (ft)
      unit_of_measurement: ft
      icon_template: mdi:image-filter-hdr
      availability_template: "{{ has_value('sensor.tesla_elevation') }}"
      value_template: >
        {% if has_value('sensor.tesla_elevation') %}
          {{ (states('sensor.tesla_elevation') | float / 3.2808) | round(2) }}
        {% endif %}

    tesla_tpms_pressure_fl_psi:
      friendly_name: Front Left Tire Pressure (psi)
      unit_of_measurement: psi
      icon_template: mdi:car-tire-alert
      availability_template: "{{ has_value('sensor.tesla_tpms_fl') }}"
      value_template: >
        {% if has_value('sensor.tesla_tpms_fl') %}
          {{ (states('sensor.tesla_tpms_fl') | float / 14.50377) | round(2) }}
        {% endif %}

    tesla_tpms_pressure_fr_psi:
      friendly_name: Front Right Tire Pressure (psi)
      unit_of_measurement: psi
      icon_template: mdi:car-tire-alert
      availability_template: "{{ has_value('sensor.tesla_tpms_fr') }}"
      value_template: >
        {% if has_value('sensor.tesla_tpms_fr') %}
          {{ (states('sensor.tesla_tpms_fr') | float / 14.50377) | round(2) }}
        {% endif %}

    tesla_tpms_pressure_rl_psi:
      friendly_name: Rear Left Tire Pressure (psi)
      unit_of_measurement: psi
      icon_template: mdi:car-tire-alert
      availability_template: "{{ has_value('sensor.tesla_tpms_rl') }}"
      value_template: >
        {% if has_value('sensor.tesla_tpms_rl') %}
          {{ (states('sensor.tesla_tpms_rl') | float / 14.50377) | round(2) }}
        {% endif %}

    tesla_tpms_pressure_rr_psi:
      friendly_name: Rear Right Tire Pressure (psi)
      unit_of_measurement: psi
      icon_template: mdi:car-tire-alert
      availability_template: "{{ has_value('sensor.tesla_tpms_rr') }}"
      value_template: >
        {% if has_value('sensor.tesla_tpms_rr') %}
          {{ (states('sensor.tesla_tpms_rr') | float / 14.50377) | round(2) }}
        {% endif %}

    tesla_active_route_distance_to_arrival_km:
      friendly_name: Active route distance to arrival (km)
      unit_of_measurement: km
      icon_template: mdi:map-marker-distance
      availability_template: "{{ has_value('sensor.tesla_active_route_distance_to_arrival_mi') }}"
      value_template: >
        {% if has_value('sensor.tesla_active_route_distance_to_arrival_mi') %}
          {{ (states('sensor.tesla_active_route_distance_to_arrival_mi') | float / 1.609344) | round(2) }}
        {% endif %}
```

**Comment by brianmay** [comment]
I modified all the `sensor.yaml` values and the `mqtt.yaml` (the docs call this `mqtt_sensors.yaml`) values also.

**Comment by longzheng** [comment]
> I modified all the `sensor.yaml` values and the `mqtt.yaml` (the docs call this `mqtt_sensors.yaml`) values also.

I tried a few things and couldn't repro that exact error. Could you share what is the state of your `sensor.tesla_est_battery_range_km`?

**Comment by brianmay** [comment]
I suspect the problem is when restarting home-assistant, it temporarily has an invalid value. But don't see this error right now, and sensor.tesla_est_battery_range_km looks valid. What I do see, after restarting the server, is:

```
Oct 13 08:19:07 iot2 homeassistant[177286]: 2024-10-13 08:19:07.683 ERROR (MainThread) [homeassistant.core] Error running job: <Job onetime listen homeassistant_start <function _async_at_core_state.<locals>._matched_event at 0x7f33728bbec0> HassJobType.Callback <_OneTimeListener homeassistant.helpers.start:<function _async_at_core_state.<locals>._matched_event at 0x7f33728bbec0>>>
Oct 13 08:19:07 iot2 homeassistant[177286]: Traceback (most recent call last):
Oct 13 08:19:07 iot2 homeassistant[177286]:   File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 658, in state
Oct 13 08:19:07 iot2 homeassistant[177286]:     numerical_value = int(value)
Oct 13 08:19:07 iot2 homeassistant[177286]:                       ^^^^^^^^^^
Oct 13 08:19:07 iot2 homeassistant[177286]: ValueError: invalid literal for int() with base 10: ''
Oct 13 08:19:07 iot2 homeassistant[177286]:
Oct 13 08:19:07 iot2 homeassistant[177286]: During handling of the above exception, another exception occurred:
Oct 13 08:19:07 iot2 homeassistant[177286]:
Oct 13 08:19:07 iot2 homeassistant[177286]: Traceback (most recent call last):
Oct 13 08:19:07 iot2 homeassistant[177286]:   File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 661, in state
Oct 13 08:19:07 iot2 homeassistant[177286]:     numerical_value = float(value)
Oct 13 08:19:07 iot2 homeassistant[177286]:                       ^^^^^^^^^^^^
Oct 13 08:19:07 iot2 homeassistant[177286]: ValueError: could not convert string to float: ''
Oct 13 08:19:07 iot2 homeassistant[177286]:
Oct 13 08:19:07 iot2 homeassistant[177286]: The above exception was the direct cause of the following exception:
Oct 13 08:19:07 iot2 homeassistant[177286]:
Oct 13 08:19:07 iot2 homeassistant[177286]: Traceback (most recent call last):
Oct 13 08:19:07 iot2 homeassistant[177286]:   File "/usr/src/homeassistant/homeassistant/core.py", line 1571, in async_fire_internal
Oct 13 08:19:07 iot2 homeassistant[177286]:     self._hass.async_run_hass_job(job, event)
Oct 13 08:19:07 iot2 homeassistant[177286]:   File "/usr/src/homeassistant/homeassistant/core.py", line 947, in async_run_hass_job
Oct 13 08:19:07 iot2 homeassistant[177286]:     hassjob.target(*args)
Oct 13 08:19:07 iot2 homeassistant[177286]:   File "/usr/src/homeassistant/homeassistant/core.py", line 1429, in __call__
Oct 13 08:19:07 iot2 homeassistant[177286]:     self.hass.async_run_hass_job(self.listener_job, event)
Oct 13 08:19:07 iot2 homeassistant[177286]:   File "/usr/src/homeassistant/homeassistant/core.py", line 947, in async_run_hass_job
Oct 13 08:19:07 iot2 homeassistant[177286]:     hassjob.target(*args)
Oct 13 08:19:07 iot2 homeassistant[177286]:   File "/usr/src/homeassistant/homeassistant/helpers/start.py", line 44, in _matched_event
Oct 13 08:19:07 iot2 homeassistant[177286]:     hass.async_run_hass_job(at_start_job, hass)
Oct 13 08:19:07 iot2 homeassistant[177286]:   File "/usr/src/homeassistant/homeassistant/core.py", line 947, in async_run_hass_job
Oct 13 08:19:07 iot2 homeassistant[177286]:     hassjob.target(*args)
Oct 13 08:19:07 iot2 homeassistant[177286]:   File "/usr/src/homeassistant/homeassistant/components/template/template_entity.py", line 487, in _async_template_startup
Oct 13 08:19:07 iot2 homeassistant[177286]:     result_info.async_refresh()
Oct 13 08:19:07 iot2 homeassistant[177286]:   File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1065, in async_refresh
Oct 13 08:19:07 iot2 homeassistant[177286]:     self._refresh(None)
Oct 13 08:19:07 iot2 homeassistant[177286]:   File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1251, in _refresh
Oct 13 08:19:07 iot2 homeassistant[177286]:     self.hass.async_run_hass_job(self._job, event, updates)
Oct 13 08:19:07 iot2 homeassistant[177286]:   File "/usr/src/homeassistant/homeassistant/core.py", line 947, in async_run_hass_job
Oct 13 08:19:07 iot2 homeassistant[177286]:     hassjob.target(*args)
Oct 13 08:19:07 iot2 homeassistant[177286]:   File "/usr/src/homeassistant/homeassistant/components/template/template_entity.py", line 435, in _handle_results
Oct 13 08:19:07 iot2 homeassistant[177286]:     self.async_write_ha_state()
Oct 13 08:19:07 iot2 homeassistant[177286]:   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1009, in async_write_ha_state
Oct 13 08:19:07 iot2 homeassistant[177286]:     self._async_write_ha_state()
Oct 13 08:19:07 iot2 homeassistant[177286]:   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1132, in _async_write_ha_state
Oct 13 08:19:07 iot2 homeassistant[177286]:     state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
Oct 13 08:19:07 iot2 homeassistant[177286]:                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 13 08:19:07 iot2 homeassistant[177286]:   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1067, in __async_calculate_state
Oct 13 08:19:07 iot2 homeassistant[177286]:     state = self._stringify_state(available)
Oct 13 08:19:07 iot2 homeassistant[177286]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 13 08:19:07 iot2 homeassistant[177286]:   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1015, in _stringify_state
Oct 13 08:19:07 iot2 homeassistant[177286]:     if (state := self.state) is None:
Oct 13 08:19:07 iot2 homeassistant[177286]:                  ^^^^^^^^^^
Oct 13 08:19:07 iot2 homeassistant[177286]:   File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 665, in state
Oct 13 08:19:07 iot2 homeassistant[177286]:     raise ValueError(
Oct 13 08:19:07 iot2 homeassistant[177286]: ValueError: Sensor sensor.tesla_active_route_distance_to_arrival_km has device class 'None', state class 'None' unit 'km' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: '' (<class 'str'>)
```

(several other messages not related to teslamate omitted)

The relevant config for this is, in `sensor.yaml` is:

```
    tesla_active_route_distance_to_arrival_km:
      friendly_name: Active route distance to arrival (km)
      unit_of_measurement: km
      icon_template: mdi:map-marker-distance
      value_template: >
        {% if has_value('sensor.tesla_active_route_distance_to_arrival_mi') %}
          {{ (states('sensor.tesla_active_route_distance_to_arrival_mi') | float * 1.609344) | round(2) }}
        {% endif %}
```

Is there some way I can tell home-assistant that none is a valid value? Alternatively is there something else I should be doing here?

**Comment by longzheng** [comment]
> The relevant config for this is, in `sensor.yaml` is:
> 
> ```
>     tesla_active_route_distance_to_arrival_km:
>       friendly_name: Active route distance to arrival (km)
>       unit_of_measurement: km
>       icon_template: mdi:map-marker-distance
>       value_template: >
>         {% if has_value('sensor.tesla_active_route_distance_to_arrival_mi') %}
>           {{ (states('sensor.tesla_active_route_distance_to_arrival_mi') | float * 1.609344) | round(2) }}
>         {% endif %}
> ```

Oh are you missing the `availability_template` property?

```yaml
    tesla_active_route_distance_to_arrival_km:
      friendly_name: Active route distance to arrival (km)
      unit_of_measurement: km
      icon_template: mdi:map-marker-distance
      availability_template: "{{ has_value('sensor.tesla_active_route_distance_to_arrival_mi') }}"
      value_template: >
        {% if has_value('sensor.tesla_active_route_distance_to_arrival_mi') %}
          {{ (states('sensor.tesla_active_route_distance_to_arrival_mi') | float / 1.609344) | round(2) }}
        {% endif %}
```

**Comment by brianmay** [comment]
Yes, that will be it.

Now just getting 4 errors on restart that have nothing to do with home-assistant.

**Comment by longzheng** [comment]
Ah cool, I'll add those `sensor.yaml` changes to the PR as well.

**Comment by JakobLichterfeld** [comment]
> Ah cool, I'll add those `sensor.yaml` changes to the PR as well.

Awesome, thanks for investigation!
