### ISSUE TITLE
Teslamate and postgres Synology docker connection problem

### ISSUE THREAD

**Issue by dobunzli** [teslamate-org/teslamate#4458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

As discussed here [https://github.com/teslamate-org/teslamate/discussions](url) it is not possible to install Teslamate on a Synology (latest DSM 7.2.2 and container manager)

The problems seems to be the connexion between teslamate container and database container and/or the creation of the schema migrations tables.

Grafana is working well and accessible.

### Steps To Reproduce

Upload compose.yaml to your synology docker folder, use container manager to create a new project. Everything is green but teslamate is not accessible.

### Relevant log output

```shell
TESLAMATE
teslamate-teslamate-1  | 2024-12-30 13:43:19.954 [error] Could not create schema migrations table. This error usually happens due to the following:
teslamate-teslamate-1  | 
teslamate-teslamate-1  |   * The database does not exist
teslamate-teslamate-1  |   * The "schema_migrations" table, which Ecto uses for managing
teslamate-teslamate-1  |     migrations, was defined by another library
teslamate-teslamate-1  |   * There is a deadlock while migrating (such as using concurrent
teslamate-teslamate-1  |     indexes with a migration_lock)
teslamate-teslamate-1  | 
teslamate-teslamate-1  | To fix the first issue, run "mix ecto.create" for the desired MIX_ENV.
teslamate-teslamate-1  | 
teslamate-teslamate-1  | To address the second, you can run "mix ecto.drop" followed by
teslamate-teslamate-1  | "mix ecto.create", both for the desired MIX_ENV. Alternatively you may
teslamate-teslamate-1  | configure Ecto to use another table and/or repository for managing
teslamate-teslamate-1  | migrations:
teslamate-teslamate-1  | 
teslamate-teslamate-1  |     config :teslamate, TeslaMate.Repo,
teslamate-teslamate-1  |       migration_source: "some_other_table_for_schema_migrations",
teslamate-teslamate-1  |       migration_repo: AnotherRepoForSchemaMigrations
teslamate-teslamate-1  | 
teslamate-teslamate-1  | The full error report is shown below.
teslamate-teslamate-1  | 
teslamate-teslamate-1  | ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2943ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
teslamate-teslamate-1  | 
teslamate-teslamate-1  |   1. Ensuring your database is available and that you can connect to it
teslamate-teslamate-1  |   2. Tracking down slow queries and making sure they are running fast enough
teslamate-teslamate-1  |   3. Increasing the pool_size (although this increases resource consumption)
teslamate-teslamate-1  |   4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
teslamate-teslamate-1  | 
teslamate-teslamate-1  | See DBConnection.start_link/2 for more information
teslamate-teslamate-1  | 
teslamate-teslamate-1  |     (ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:1096: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate-teslamate-1  |     (elixir 1.17.3) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
teslamate-teslamate-1  |     (ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:1203: Ecto.Adapters.SQL.execute_ddl/4
teslamate-teslamate-1  |     (ecto_sql 3.12.1) lib/ecto/migrator.ex:779: Ecto.Migrator.verbose_schema_migration/3
teslamate-teslamate-1  |     (ecto_sql 3.12.1) lib/ecto/migrator.ex:563: Ecto.Migrator.lock_for_migrations/4
teslamate-teslamate-1  |     (ecto_sql 3.12.1) lib/ecto/migrator.ex:432: Ecto.Migrator.run/4
teslamate-teslamate-1  |     (ecto_sql 3.12.1) lib/ecto/migrator.ex:170: Ecto.Migrator.with_repo/3
teslamate-teslamate-1  |     nofile:1: (file)
teslamate-teslamate-1  | waiting for postgres at database:5432
teslamate-teslamate-1  | waiting for postgres at database:5432
teslamate-teslamate-1  | waiting for postgres at database:5432

DATABASE IS RUNNING

teslamate-database-1   | 
teslamate-database-1   | PostgreSQL Database directory appears to contain a database; Skipping initialization
teslamate-database-1   | 
teslamate-database-1   | 2024-12-30 13:14:16.775 UTC [1] LOG:  starting PostgreSQL 17.2 (Debian 17.2-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
teslamate-database-1   | 2024-12-30 13:14:16.775 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
teslamate-database-1   | 2024-12-30 13:14:16.775 UTC [1] LOG:  listening on IPv6 address "::", port 5432
teslamate-database-1   | 2024-12-30 13:14:16.939 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
teslamate-database-1   | 2024-12-30 13:14:17.086 UTC [27] LOG:  database system was shut down at 2024-12-30 13:13:53 UTC
teslamate-database-1   | 2024-12-30 13:14:17.118 UTC [1] LOG:  database system is ready to accept connections

### Additional data

compose.yaml file

services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    environment:
      - ENCRYPTION_KEY=mypass #replace with a secure key to encrypt your Tesla API tokens
      - DATABASE_USER=teslamate
      - DATABASE_PASS=mypass #insert your secure database password!
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - DATABASE_POOL_SIZE=40
      - MQTT_HOST=mosquitto
    ports:
      - 4000:4000
    volumes:
      - /volume1/docker/TeslaMate/import:/opt/app/import
    cap_drop:
      - all

  database:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=mypass #insert your secure database password!
      - POSTGRES_DB=teslamate
    volumes:
      - /volume1/docker/TeslaMate/teslamate-db:/var/lib/postgresql/data

  grafana:
    image: teslamate/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=mypass #insert your secure database password!
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
    ports:
      - 3000:3000
    volumes:
      - /volume1/docker/TeslaMate/teslamate-grafana-data:/var/lib/grafana

  mosquitto:
    image: eclipse-mosquitto:2
    restart: always
    command: mosquitto -c /mosquitto-no-auth.conf
    # ports:
    #   - 1883:1883
    volumes:
      - /volume1/docker/TeslaMate/mosquitto-conf:/mosquitto/config
      - /volume1/docker/TeslaMate/mosquitto-data:/mosquitto/data

volumes:
  teslamate-db:
  teslamate-grafana-data:
  mosquitto-conf:
  mosquitto-data:

### Type of installation

Docker

### Version

latest

### Already tried without success

- instead of DATABASE_PATH: database --> IP of the database container
- DATABASE_POOL_SIZE = 40

**Comment by Zi0u** [comment]
Hi, 
Did you check permissions on folders and firewall settings of Synology ?

**Comment by dobunzli** [comment]
I erased everything and reinstalled it by using Portainer.io, but exact same problem and errors...
I give up for now !

**Comment by dobunzli** [comment]
Hello, back again ! I solved it !

No bug but misconfigurations. I hope this helps someone else.

I think that three things were needed :

1. Permissions: be sure to add SYSTEM to teslamate docker folder with read and write access

2. DATABASE_PASS, POSTGRES_PASSWORD, DATABASE_PASS in your yml file have to be the three times the same !

3. Be sure to have your firewall deactivated completely during install and not only ports 4000 and 3000 which is not sufficient for installation ! 
Opening also port 5432 didn’t work either (which is used by postgreSQL). 
I had to completely deactivate the firewall.

Regarding to port forwarding Grafana and teslamate don’t work with only 3000 and 4000 opened (nxdomain errors, sql connexions error etc…). 

Do you know what exact minimal port configuration is needed so that it works  ? I wish to use it only on my local network.

Thanks.

**Comment by SkyLostTR** [comment]
Those three steps and allowing Docker subnet on the Synology firewall work pretty well. Thanks for your help. Fixed my problem also.
